using System.IO;
using System.Runtime.Serialization;
using WolvenKit.CR2W.Reflection;
using static WolvenKit.CR2W.Types.Enums;


namespace WolvenKit.CR2W.Types
{
	[DataContract(Namespace = "")]
	[REDMeta]
	public class W3GameParams : CObject
	{
		[RED("dm")] 		public CHandle<CDefinitionsManagerAccessor> Dm { get; set;}

		[RED("main")] 		public SCustomNode Main { get; set;}

		[RED("BASE_ABILITY_TAG")] 		public CName BASE_ABILITY_TAG { get; set;}

		[RED("PASSIVE_BONUS_ABILITY_TAG")] 		public CName PASSIVE_BONUS_ABILITY_TAG { get; set;}

		[RED("forbiddenAttributes", 2,0)] 		public CArray<CName> ForbiddenAttributes { get; set;}

		[RED("GLOBAL_ENEMY_ABILITY")] 		public CName GLOBAL_ENEMY_ABILITY { get; set;}

		[RED("ENEMY_BONUS_PER_LEVEL")] 		public CName ENEMY_BONUS_PER_LEVEL { get; set;}

		[RED("ENEMY_BONUS_FISTFIGHT_LOW")] 		public CName ENEMY_BONUS_FISTFIGHT_LOW { get; set;}

		[RED("ENEMY_BONUS_FISTFIGHT_HIGH")] 		public CName ENEMY_BONUS_FISTFIGHT_HIGH { get; set;}

		[RED("ENEMY_BONUS_LOW")] 		public CName ENEMY_BONUS_LOW { get; set;}

		[RED("ENEMY_BONUS_HIGH")] 		public CName ENEMY_BONUS_HIGH { get; set;}

		[RED("ENEMY_BONUS_DEADLY")] 		public CName ENEMY_BONUS_DEADLY { get; set;}

		[RED("MONSTER_BONUS_PER_LEVEL")] 		public CName MONSTER_BONUS_PER_LEVEL { get; set;}

		[RED("MONSTER_BONUS_PER_LEVEL_GROUP")] 		public CName MONSTER_BONUS_PER_LEVEL_GROUP { get; set;}

		[RED("MONSTER_BONUS_PER_LEVEL_ARMORED")] 		public CName MONSTER_BONUS_PER_LEVEL_ARMORED { get; set;}

		[RED("MONSTER_BONUS_PER_LEVEL_GROUP_ARMORED")] 		public CName MONSTER_BONUS_PER_LEVEL_GROUP_ARMORED { get; set;}

		[RED("MONSTER_BONUS_LOW")] 		public CName MONSTER_BONUS_LOW { get; set;}

		[RED("MONSTER_BONUS_HIGH")] 		public CName MONSTER_BONUS_HIGH { get; set;}

		[RED("MONSTER_BONUS_DEADLY")] 		public CName MONSTER_BONUS_DEADLY { get; set;}

		[RED("BOSS_NGP_BONUS")] 		public CName BOSS_NGP_BONUS { get; set;}

		[RED("GLOBAL_PLAYER_ABILITY")] 		public CName GLOBAL_PLAYER_ABILITY { get; set;}

		[RED("NOT_A_SKILL_ABILITY_TAG")] 		public CName NOT_A_SKILL_ABILITY_TAG { get; set;}

		[RED("ALCHEMY_COOKED_ITEM_TYPE_POTION")] 		public CString ALCHEMY_COOKED_ITEM_TYPE_POTION { get; set;}

		[RED("ALCHEMY_COOKED_ITEM_TYPE_BOMB")] 		public CString ALCHEMY_COOKED_ITEM_TYPE_BOMB { get; set;}

		[RED("ALCHEMY_COOKED_ITEM_TYPE_OIL")] 		public CString ALCHEMY_COOKED_ITEM_TYPE_OIL { get; set;}

		[RED("OIL_ABILITY_TAG")] 		public CName OIL_ABILITY_TAG { get; set;}

		[RED("QUANTITY_INCREASED_BY_ALCHEMY_TABLE")] 		public CInt32 QUANTITY_INCREASED_BY_ALCHEMY_TABLE { get; set;}

		[RED("ATTACK_NAME_LIGHT")] 		public CName ATTACK_NAME_LIGHT { get; set;}

		[RED("ATTACK_NAME_HEAVY")] 		public CName ATTACK_NAME_HEAVY { get; set;}

		[RED("ATTACK_NAME_SUPERHEAVY")] 		public CName ATTACK_NAME_SUPERHEAVY { get; set;}

		[RED("ATTACK_NAME_SPEED_BASED")] 		public CName ATTACK_NAME_SPEED_BASED { get; set;}

		[RED("ATTACK_NO_DAMAGE")] 		public CName ATTACK_NO_DAMAGE { get; set;}

		[RED("MAX_DYNAMICALLY_SPAWNED_BOATS")] 		public CInt32 MAX_DYNAMICALLY_SPAWNED_BOATS { get; set;}

		[RED("MAX_THROW_RANGE")] 		public CFloat MAX_THROW_RANGE { get; set;}

		[RED("UNDERWATER_THROW_RANGE")] 		public CFloat UNDERWATER_THROW_RANGE { get; set;}

		[RED("PROXIMITY_PETARD_IDLE_DETONATION_TIME")] 		public CFloat PROXIMITY_PETARD_IDLE_DETONATION_TIME { get; set;}

		[RED("BOMB_THROW_DELAY")] 		public CFloat BOMB_THROW_DELAY { get; set;}

		[RED("CONTAINER_DYNAMIC_DESTROY_TIMEOUT")] 		public CInt32 CONTAINER_DYNAMIC_DESTROY_TIMEOUT { get; set;}

		[RED("CRITICAL_HIT_CHANCE")] 		public CName CRITICAL_HIT_CHANCE { get; set;}

		[RED("CRITICAL_HIT_DAMAGE_BONUS")] 		public CName CRITICAL_HIT_DAMAGE_BONUS { get; set;}

		[RED("CRITICAL_HIT_REDUCTION")] 		public CName CRITICAL_HIT_REDUCTION { get; set;}

		[RED("CRITICAL_HIT_FX")] 		public CName CRITICAL_HIT_FX { get; set;}

		[RED("HEAD_SHOT_CRIT_CHANCE_BONUS")] 		public CFloat HEAD_SHOT_CRIT_CHANCE_BONUS { get; set;}

		[RED("BACK_ATTACK_CRIT_CHANCE_BONUS")] 		public CFloat BACK_ATTACK_CRIT_CHANCE_BONUS { get; set;}

		[RED("DAMAGE_NAME_DIRECT")] 		public CName DAMAGE_NAME_DIRECT { get; set;}

		[RED("DAMAGE_NAME_PHYSICAL")] 		public CName DAMAGE_NAME_PHYSICAL { get; set;}

		[RED("DAMAGE_NAME_SILVER")] 		public CName DAMAGE_NAME_SILVER { get; set;}

		[RED("DAMAGE_NAME_SLASHING")] 		public CName DAMAGE_NAME_SLASHING { get; set;}

		[RED("DAMAGE_NAME_PIERCING")] 		public CName DAMAGE_NAME_PIERCING { get; set;}

		[RED("DAMAGE_NAME_BLUDGEONING")] 		public CName DAMAGE_NAME_BLUDGEONING { get; set;}

		[RED("DAMAGE_NAME_RENDING")] 		public CName DAMAGE_NAME_RENDING { get; set;}

		[RED("DAMAGE_NAME_ELEMENTAL")] 		public CName DAMAGE_NAME_ELEMENTAL { get; set;}

		[RED("DAMAGE_NAME_FIRE")] 		public CName DAMAGE_NAME_FIRE { get; set;}

		[RED("DAMAGE_NAME_FORCE")] 		public CName DAMAGE_NAME_FORCE { get; set;}

		[RED("DAMAGE_NAME_FROST")] 		public CName DAMAGE_NAME_FROST { get; set;}

		[RED("DAMAGE_NAME_POISON")] 		public CName DAMAGE_NAME_POISON { get; set;}

		[RED("DAMAGE_NAME_SHOCK")] 		public CName DAMAGE_NAME_SHOCK { get; set;}

		[RED("DAMAGE_NAME_MORALE")] 		public CName DAMAGE_NAME_MORALE { get; set;}

		[RED("DAMAGE_NAME_STAMINA")] 		public CName DAMAGE_NAME_STAMINA { get; set;}

		[RED("FOCUS_DRAIN_PER_HIT")] 		public CFloat FOCUS_DRAIN_PER_HIT { get; set;}

		[RED("UNINTERRUPTED_HITS_CAMERA_EFFECT_REGULAR_ENEMY")] 		public CName UNINTERRUPTED_HITS_CAMERA_EFFECT_REGULAR_ENEMY { get; set;}

		[RED("UNINTERRUPTED_HITS_CAMERA_EFFECT_BIG_ENEMY")] 		public CName UNINTERRUPTED_HITS_CAMERA_EFFECT_BIG_ENEMY { get; set;}

		[RED("MONSTER_RESIST_THRESHOLD_TO_REFLECT_FISTS")] 		public CFloat MONSTER_RESIST_THRESHOLD_TO_REFLECT_FISTS { get; set;}

		[RED("ARMOR_VALUE_NAME")] 		public CName ARMOR_VALUE_NAME { get; set;}

		[RED("LOW_HEALTH_EFFECT_SHOW")] 		public CFloat LOW_HEALTH_EFFECT_SHOW { get; set;}

		[RED("UNDERWATER_CROSSBOW_DAMAGE_BONUS")] 		public CFloat UNDERWATER_CROSSBOW_DAMAGE_BONUS { get; set;}

		[RED("UNDERWATER_CROSSBOW_DAMAGE_BONUS_NGP")] 		public CFloat UNDERWATER_CROSSBOW_DAMAGE_BONUS_NGP { get; set;}

		[RED("ARCHER_DAMAGE_BONUS_NGP")] 		public CFloat ARCHER_DAMAGE_BONUS_NGP { get; set;}

		[RED("IGNI_SPELL_POWER_MILT")] 		public CFloat IGNI_SPELL_POWER_MILT { get; set;}

		[RED("INSTANT_KILL_INTERNAL_PLAYER_COOLDOWN")] 		public CFloat INSTANT_KILL_INTERNAL_PLAYER_COOLDOWN { get; set;}

		[RED("DIFFICULTY_TAG_EASY")] 		public CName DIFFICULTY_TAG_EASY { get; set;}

		[RED("DIFFICULTY_TAG_MEDIUM")] 		public CName DIFFICULTY_TAG_MEDIUM { get; set;}

		[RED("DIFFICULTY_TAG_HARD")] 		public CName DIFFICULTY_TAG_HARD { get; set;}

		[RED("DIFFICULTY_TAG_HARDCORE")] 		public CName DIFFICULTY_TAG_HARDCORE { get; set;}

		[RED("DIFFICULTY_TAG_DIFF_ABILITY")] 		public CName DIFFICULTY_TAG_DIFF_ABILITY { get; set;}

		[RED("DIFFICULTY_HP_MULTIPLIER")] 		public CName DIFFICULTY_HP_MULTIPLIER { get; set;}

		[RED("DIFFICULTY_DMG_MULTIPLIER")] 		public CName DIFFICULTY_DMG_MULTIPLIER { get; set;}

		[RED("DIFFICULTY_TAG_IGNORE")] 		public CName DIFFICULTY_TAG_IGNORE { get; set;}

		[RED("DISMEMBERMENT_ON_DEATH_CHANCE")] 		public CInt32 DISMEMBERMENT_ON_DEATH_CHANCE { get; set;}

		[RED("FINISHER_ON_DEATH_CHANCE")] 		public CInt32 FINISHER_ON_DEATH_CHANCE { get; set;}

		[RED("DURABILITY_ARMOR_LOSE_CHANCE")] 		public CInt32 DURABILITY_ARMOR_LOSE_CHANCE { get; set;}

		[RED("DURABILITY_WEAPON_LOSE_CHANCE")] 		public CInt32 DURABILITY_WEAPON_LOSE_CHANCE { get; set;}

		[RED("DURABILITY_ARMOR_LOSE_VALUE")] 		public CFloat DURABILITY_ARMOR_LOSE_VALUE { get; set;}

		[RED("DURABILITY_WEAPON_LOSE_VALUE")] 		public CFloat DURABILITY_WEAPON_LOSE_VALUE { get; set;}

		[RED("DURABILITY_WEAPON_LOSE_VALUE_HARDCORE")] 		public CFloat DURABILITY_WEAPON_LOSE_VALUE_HARDCORE { get; set;}

		[RED("DURABILITY_ARMOR_CHEST_WEIGHT")] 		public CInt32 DURABILITY_ARMOR_CHEST_WEIGHT { get; set;}

		[RED("DURABILITY_ARMOR_PANTS_WEIGHT")] 		public CInt32 DURABILITY_ARMOR_PANTS_WEIGHT { get; set;}

		[RED("DURABILITY_ARMOR_BOOTS_WEIGHT")] 		public CInt32 DURABILITY_ARMOR_BOOTS_WEIGHT { get; set;}

		[RED("DURABILITY_ARMOR_GLOVES_WEIGHT")] 		public CInt32 DURABILITY_ARMOR_GLOVES_WEIGHT { get; set;}

		[RED("DURABILITY_ARMOR_MISS_WEIGHT")] 		public CInt32 DURABILITY_ARMOR_MISS_WEIGHT { get; set;}

		[RED("durabilityThresholdsWeapon", 2,0)] 		public CArray<SDurabilityThreshold> DurabilityThresholdsWeapon { get; set;}

		[RED("durabilityThresholdsArmor", 2,0)] 		public CArray<SDurabilityThreshold> DurabilityThresholdsArmor { get; set;}

		[RED("TAG_REPAIR_CONSUMABLE_ARMOR")] 		public CName TAG_REPAIR_CONSUMABLE_ARMOR { get; set;}

		[RED("TAG_REPAIR_CONSUMABLE_STEEL")] 		public CName TAG_REPAIR_CONSUMABLE_STEEL { get; set;}

		[RED("TAG_REPAIR_CONSUMABLE_SILVER")] 		public CName TAG_REPAIR_CONSUMABLE_SILVER { get; set;}

		[RED("ITEM_DAMAGED_DURABILITY")] 		public CInt32 ITEM_DAMAGED_DURABILITY { get; set;}

		[RED("INTERACTIVE_REPAIR_OBJECT_MAX_DURS", 2,0)] 		public CArray<CInt32> INTERACTIVE_REPAIR_OBJECT_MAX_DURS { get; set;}

		[RED("CFM_SLOWDOWN_RATIO")] 		public CFloat CFM_SLOWDOWN_RATIO { get; set;}

		[RED("LIGHT_HIT_FX")] 		public CName LIGHT_HIT_FX { get; set;}

		[RED("LIGHT_HIT_BACK_FX")] 		public CName LIGHT_HIT_BACK_FX { get; set;}

		[RED("LIGHT_HIT_PARRIED_FX")] 		public CName LIGHT_HIT_PARRIED_FX { get; set;}

		[RED("LIGHT_HIT_BACK_PARRIED_FX")] 		public CName LIGHT_HIT_BACK_PARRIED_FX { get; set;}

		[RED("HEAVY_HIT_FX")] 		public CName HEAVY_HIT_FX { get; set;}

		[RED("HEAVY_HIT_BACK_FX")] 		public CName HEAVY_HIT_BACK_FX { get; set;}

		[RED("HEAVY_HIT_PARRIED_FX")] 		public CName HEAVY_HIT_PARRIED_FX { get; set;}

		[RED("HEAVY_HIT_BACK_PARRIED_FX")] 		public CName HEAVY_HIT_BACK_PARRIED_FX { get; set;}

		[RED("LOW_HP_SHOW_LEVEL")] 		public CFloat LOW_HP_SHOW_LEVEL { get; set;}

		[RED("TAG_ARMOR")] 		public CName TAG_ARMOR { get; set;}

		[RED("TAG_ENCUMBRANCE_ITEM_FORCE_YES")] 		public CName TAG_ENCUMBRANCE_ITEM_FORCE_YES { get; set;}

		[RED("TAG_ENCUMBRANCE_ITEM_FORCE_NO")] 		public CName TAG_ENCUMBRANCE_ITEM_FORCE_NO { get; set;}

		[RED("TAG_ITEM_UPGRADEABLE")] 		public CName TAG_ITEM_UPGRADEABLE { get; set;}

		[RED("TAG_DONT_SHOW")] 		public CName TAG_DONT_SHOW { get; set;}

		[RED("TAG_DONT_SHOW_ONLY_IN_PLAYERS")] 		public CName TAG_DONT_SHOW_ONLY_IN_PLAYERS { get; set;}

		[RED("TAG_ITEM_SINGLETON")] 		public CName TAG_ITEM_SINGLETON { get; set;}

		[RED("TAG_INFINITE_AMMO")] 		public CName TAG_INFINITE_AMMO { get; set;}

		[RED("TAG_UNDERWATER_AMMO")] 		public CName TAG_UNDERWATER_AMMO { get; set;}

		[RED("TAG_GROUND_AMMO")] 		public CName TAG_GROUND_AMMO { get; set;}

		[RED("TAG_ILLUSION_MEDALLION")] 		public CName TAG_ILLUSION_MEDALLION { get; set;}

		[RED("TAG_PLAYER_STEELSWORD")] 		public CName TAG_PLAYER_STEELSWORD { get; set;}

		[RED("TAG_PLAYER_SILVERSWORD")] 		public CName TAG_PLAYER_SILVERSWORD { get; set;}

		[RED("TAG_INFINITE_USE")] 		public CName TAG_INFINITE_USE { get; set;}

		[RED("ARMOR_MASTERWORK_ABILITIES", 2,0)] 		public CArray<CName> ARMOR_MASTERWORK_ABILITIES { get; set;}

		[RED("ARMOR_MAGICAL_ABILITIES", 2,0)] 		public CArray<CName> ARMOR_MAGICAL_ABILITIES { get; set;}

		[RED("GLOVES_MASTERWORK_ABILITIES", 2,0)] 		public CArray<CName> GLOVES_MASTERWORK_ABILITIES { get; set;}

		[RED("GLOVES_MAGICAL_ABILITIES", 2,0)] 		public CArray<CName> GLOVES_MAGICAL_ABILITIES { get; set;}

		[RED("PANTS_MASTERWORK_ABILITIES", 2,0)] 		public CArray<CName> PANTS_MASTERWORK_ABILITIES { get; set;}

		[RED("PANTS_MAGICAL_ABILITIES", 2,0)] 		public CArray<CName> PANTS_MAGICAL_ABILITIES { get; set;}

		[RED("BOOTS_MASTERWORK_ABILITIES", 2,0)] 		public CArray<CName> BOOTS_MASTERWORK_ABILITIES { get; set;}

		[RED("BOOTS_MAGICAL_ABILITIES", 2,0)] 		public CArray<CName> BOOTS_MAGICAL_ABILITIES { get; set;}

		[RED("WEAPON_MASTERWORK_ABILITIES", 2,0)] 		public CArray<CName> WEAPON_MASTERWORK_ABILITIES { get; set;}

		[RED("WEAPON_MAGICAL_ABILITIES", 2,0)] 		public CArray<CName> WEAPON_MAGICAL_ABILITIES { get; set;}

		[RED("ITEM_SET_TAG_BEAR")] 		public CName ITEM_SET_TAG_BEAR { get; set;}

		[RED("ITEM_SET_TAG_GRYPHON")] 		public CName ITEM_SET_TAG_GRYPHON { get; set;}

		[RED("ITEM_SET_TAG_LYNX")] 		public CName ITEM_SET_TAG_LYNX { get; set;}

		[RED("ITEM_SET_TAG_WOLF")] 		public CName ITEM_SET_TAG_WOLF { get; set;}

		[RED("ITEM_SET_TAG_RED_WOLF")] 		public CName ITEM_SET_TAG_RED_WOLF { get; set;}

		[RED("ITEM_SET_TAG_VAMPIRE")] 		public CName ITEM_SET_TAG_VAMPIRE { get; set;}

		[RED("ITEM_SET_TAG_VIPER")] 		public CName ITEM_SET_TAG_VIPER { get; set;}

		[RED("BOUNCE_ARROWS_ABILITY")] 		public CName BOUNCE_ARROWS_ABILITY { get; set;}

		[RED("TAG_ALCHEMY_REFILL_ALCO")] 		public CName TAG_ALCHEMY_REFILL_ALCO { get; set;}

		[RED("REPAIR_OBJECT_BONUS_ARMOR_ABILITY")] 		public CName REPAIR_OBJECT_BONUS_ARMOR_ABILITY { get; set;}

		[RED("REPAIR_OBJECT_BONUS_WEAPON_ABILITY")] 		public CName REPAIR_OBJECT_BONUS_WEAPON_ABILITY { get; set;}

		[RED("REPAIR_OBJECT_BONUS")] 		public CName REPAIR_OBJECT_BONUS { get; set;}

		[RED("CIRI_SWORD_NAME")] 		public CName CIRI_SWORD_NAME { get; set;}

		[RED("TAG_OFIR_SET")] 		public CName TAG_OFIR_SET { get; set;}

		[RED("newGamePlusLevel")] 		public CInt32 NewGamePlusLevel { get; set;}

		[RED("NEW_GAME_PLUS_LEVEL_ADD")] 		public CInt32 NEW_GAME_PLUS_LEVEL_ADD { get; set;}

		[RED("NEW_GAME_PLUS_MIN_LEVEL")] 		public CInt32 NEW_GAME_PLUS_MIN_LEVEL { get; set;}

		[RED("NEW_GAME_PLUS_EP1_MIN_LEVEL")] 		public CInt32 NEW_GAME_PLUS_EP1_MIN_LEVEL { get; set;}

		[RED("TAG_STEEL_OIL")] 		public CName TAG_STEEL_OIL { get; set;}

		[RED("TAG_SILVER_OIL")] 		public CName TAG_SILVER_OIL { get; set;}

		[RED("HEAVY_STRIKE_COST_MULTIPLIER")] 		public CFloat HEAVY_STRIKE_COST_MULTIPLIER { get; set;}

		[RED("PARRY_HALF_ANGLE")] 		public CInt32 PARRY_HALF_ANGLE { get; set;}

		[RED("PARRY_STAGGER_REDUCE_DAMAGE_LARGE")] 		public CFloat PARRY_STAGGER_REDUCE_DAMAGE_LARGE { get; set;}

		[RED("PARRY_STAGGER_REDUCE_DAMAGE_SMALL")] 		public CFloat PARRY_STAGGER_REDUCE_DAMAGE_SMALL { get; set;}

		[RED("POTION_QUICKSLOTS_COUNT")] 		public CInt32 POTION_QUICKSLOTS_COUNT { get; set;}

		[RED("ITEMS_REQUIRED_FOR_MINOR_SET_BONUS")] 		public CInt32 ITEMS_REQUIRED_FOR_MINOR_SET_BONUS { get; set;}

		[RED("ITEMS_REQUIRED_FOR_MAJOR_SET_BONUS")] 		public CInt32 ITEMS_REQUIRED_FOR_MAJOR_SET_BONUS { get; set;}

		[RED("ITEM_SET_TAG_BONUS")] 		public CName ITEM_SET_TAG_BONUS { get; set;}

		[RED("TAG_STEEL_SOCKETABLE")] 		public CName TAG_STEEL_SOCKETABLE { get; set;}

		[RED("TAG_SILVER_SOCKETABLE")] 		public CName TAG_SILVER_SOCKETABLE { get; set;}

		[RED("TAG_ARMOR_SOCKETABLE")] 		public CName TAG_ARMOR_SOCKETABLE { get; set;}

		[RED("TAG_ABILITY_SOCKET")] 		public CName TAG_ABILITY_SOCKET { get; set;}

		[RED("STAMINA_COST_PARRY_ATTRIBUTE")] 		public CName STAMINA_COST_PARRY_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_COUNTERATTACK_ATTRIBUTE")] 		public CName STAMINA_COST_COUNTERATTACK_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_EVADE_ATTRIBUTE")] 		public CName STAMINA_COST_EVADE_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_SWIMMING_PER_SEC_ATTRIBUTE")] 		public CName STAMINA_COST_SWIMMING_PER_SEC_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_SUPER_HEAVY_ACTION_ATTRIBUTE")] 		public CName STAMINA_COST_SUPER_HEAVY_ACTION_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_HEAVY_ACTION_ATTRIBUTE")] 		public CName STAMINA_COST_HEAVY_ACTION_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_LIGHT_ACTION_ATTRIBUTE")] 		public CName STAMINA_COST_LIGHT_ACTION_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_DODGE_ATTRIBUTE")] 		public CName STAMINA_COST_DODGE_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_SPRINT_ATTRIBUTE")] 		public CName STAMINA_COST_SPRINT_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_SPRINT_PER_SEC_ATTRIBUTE")] 		public CName STAMINA_COST_SPRINT_PER_SEC_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_JUMP_ATTRIBUTE")] 		public CName STAMINA_COST_JUMP_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_USABLE_ITEM_ATTRIBUTE")] 		public CName STAMINA_COST_USABLE_ITEM_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_DEFAULT")] 		public CName STAMINA_COST_DEFAULT { get; set;}

		[RED("STAMINA_COST_PER_SEC_DEFAULT")] 		public CName STAMINA_COST_PER_SEC_DEFAULT { get; set;}

		[RED("STAMINA_COST_ROLL_ATTRIBUTE")] 		public CName STAMINA_COST_ROLL_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_LIGHT_SPECIAL_ATTRIBUTE")] 		public CName STAMINA_COST_LIGHT_SPECIAL_ATTRIBUTE { get; set;}

		[RED("STAMINA_COST_HEAVY_SPECIAL_ATTRIBUTE")] 		public CName STAMINA_COST_HEAVY_SPECIAL_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_PARRY_ATTRIBUTE")] 		public CName STAMINA_DELAY_PARRY_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_COUNTERATTACK_ATTRIBUTE")] 		public CName STAMINA_DELAY_COUNTERATTACK_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_EVADE_ATTRIBUTE")] 		public CName STAMINA_DELAY_EVADE_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_SWIMMING_ATTRIBUTE")] 		public CName STAMINA_DELAY_SWIMMING_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_SUPER_HEAVY_ACTION_ATTRIBUTE")] 		public CName STAMINA_DELAY_SUPER_HEAVY_ACTION_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_HEAVY_ACTION_ATTRIBUTE")] 		public CName STAMINA_DELAY_HEAVY_ACTION_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_LIGHT_ACTION_ATTRIBUTE")] 		public CName STAMINA_DELAY_LIGHT_ACTION_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_DODGE_ATTRIBUTE")] 		public CName STAMINA_DELAY_DODGE_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_SPRINT_ATTRIBUTE")] 		public CName STAMINA_DELAY_SPRINT_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_JUMP_ATTRIBUTE")] 		public CName STAMINA_DELAY_JUMP_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_USABLE_ITEM_ATTRIBUTE")] 		public CName STAMINA_DELAY_USABLE_ITEM_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_DEFAULT")] 		public CName STAMINA_DELAY_DEFAULT { get; set;}

		[RED("STAMINA_DELAY_ROLL_ATTRIBUTE")] 		public CName STAMINA_DELAY_ROLL_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_LIGHT_SPECIAL_ATTRIBUTE")] 		public CName STAMINA_DELAY_LIGHT_SPECIAL_ATTRIBUTE { get; set;}

		[RED("STAMINA_DELAY_HEAVY_SPECIAL_ATTRIBUTE")] 		public CName STAMINA_DELAY_HEAVY_SPECIAL_ATTRIBUTE { get; set;}

		[RED("STAMINA_SEGMENT_SIZE")] 		public CInt32 STAMINA_SEGMENT_SIZE { get; set;}

		[RED("TOXICITY_DAMAGE_THRESHOLD")] 		public CFloat TOXICITY_DAMAGE_THRESHOLD { get; set;}

		[RED("DEBUG_CHEATS_ENABLED")] 		public CBool DEBUG_CHEATS_ENABLED { get; set;}

		[RED("SKILL_GLOBAL_PASSIVE_TAG")] 		public CName SKILL_GLOBAL_PASSIVE_TAG { get; set;}

		[RED("TAG_OPEN_FIRE")] 		public CName TAG_OPEN_FIRE { get; set;}

		[RED("TAG_MONSTER_SKILL")] 		public CName TAG_MONSTER_SKILL { get; set;}

		[RED("TAG_EXPLODING_GAS")] 		public CName TAG_EXPLODING_GAS { get; set;}

		[RED("ON_HIT_HP_REGEN_DELAY")] 		public CFloat ON_HIT_HP_REGEN_DELAY { get; set;}

		[RED("TAG_NPC_IN_PARTY")] 		public CName TAG_NPC_IN_PARTY { get; set;}

		[RED("TAG_PLAYERS_MOUNTED_VEHICLE")] 		public CName TAG_PLAYERS_MOUNTED_VEHICLE { get; set;}

		[RED("TAG_SOFT_LOCK")] 		public CName TAG_SOFT_LOCK { get; set;}

		[RED("MAX_SPELLPOWER_ASSUMED")] 		public CFloat MAX_SPELLPOWER_ASSUMED { get; set;}

		[RED("NPC_RESIST_PER_LEVEL")] 		public CFloat NPC_RESIST_PER_LEVEL { get; set;}

		[RED("XP_PER_LEVEL")] 		public CInt32 XP_PER_LEVEL { get; set;}

		[RED("XP_MINIBOSS_BONUS")] 		public CFloat XP_MINIBOSS_BONUS { get; set;}

		[RED("XP_BOSS_BONUS")] 		public CFloat XP_BOSS_BONUS { get; set;}

		[RED("ADRENALINE_DRAIN_AFTER_COMBAT_DELAY")] 		public CFloat ADRENALINE_DRAIN_AFTER_COMBAT_DELAY { get; set;}

		[RED("KEYBOARD_KEY_FONT_COLOR")] 		public CString KEYBOARD_KEY_FONT_COLOR { get; set;}

		[RED("MONSTER_HUNT_ACTOR_TAG")] 		public CName MONSTER_HUNT_ACTOR_TAG { get; set;}

		[RED("GWINT_CARD_ACHIEVEMENT_TAG")] 		public CName GWINT_CARD_ACHIEVEMENT_TAG { get; set;}

		[RED("TAG_AXIIABLE")] 		public CName TAG_AXIIABLE { get; set;}

		[RED("TAG_AXIIABLE_LOWER_CASE")] 		public CName TAG_AXIIABLE_LOWER_CASE { get; set;}

		[RED("LEVEL_DIFF_DEADLY")] 		public CInt32 LEVEL_DIFF_DEADLY { get; set;}

		[RED("LEVEL_DIFF_HIGH")] 		public CInt32 LEVEL_DIFF_HIGH { get; set;}

		[RED("LEVEL_DIFF_XP_MOD")] 		public CFloat LEVEL_DIFF_XP_MOD { get; set;}

		[RED("MAX_XP_MOD")] 		public CFloat MAX_XP_MOD { get; set;}

		[RED("DEVIL_HORSE_AURA_MIN_DELAY")] 		public CInt32 DEVIL_HORSE_AURA_MIN_DELAY { get; set;}

		[RED("DEVIL_HORSE_AURA_MAX_DELAY")] 		public CInt32 DEVIL_HORSE_AURA_MAX_DELAY { get; set;}

		[RED("TOTAL_AMOUNT_OF_BOOKS")] 		public CInt32 TOTAL_AMOUNT_OF_BOOKS { get; set;}

		[RED("MAX_PLAYER_LEVEL")] 		public CInt32 MAX_PLAYER_LEVEL { get; set;}

		public W3GameParams(CR2WFile cr2w, CVariable parent, string name) : base(cr2w, parent, name){ }

		public static new CVariable Create(CR2WFile cr2w, CVariable parent, string name) => new W3GameParams(cr2w, parent, name);

		public override void Read(BinaryReader file, uint size) => base.Read(file, size);

		public override void Write(BinaryWriter file) => base.Write(file);

	}
}