; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27043.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Michael\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
