// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WolvenKit.MSTests.Model;

namespace WolvenKit.MSTests.Migrations
{
    [DbContext(typeof(RedDBContext))]
    partial class RedDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("WolvenKit.MSTests.Model.RedFile", b =>
                {
                    b.Property<ulong>("RedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uses")
                        .HasColumnType("TEXT");

                    b.HasKey("RedFileId");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
