using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Media;
using WolvenKit.App.Services;
using WolvenKit.App.ViewModels.GraphEditor.Nodes;
using WolvenKit.RED4.Types;

namespace WolvenKit.App.ViewModels.GraphEditor.Nodes.Behavior;

public class BehaviorNodeViewModel : NodeViewModel, IRefreshableDetails
{
    public override uint UniqueId { get; }

    public Brush Background { get; }

    public Brush ContentBackground { get; }

    public string NodePath { get; }

    public bool IsRoot { get; }

    public BehaviorNodeViewModel(AIbehaviorTreeNodeDefinition node, uint uniqueId, string nodePath, bool isRoot) : base(node)
    {
        UniqueId = uniqueId;
        NodePath = nodePath;
        IsRoot = isRoot;
        Title = FormatBehaviorNodeName(node.GetType().Name);
        Background = GetBackgroundForNode(node);
        ContentBackground = GetContentBackgroundForNode(node);

        Input.Add(new InputConnectorViewModel("Parent", isRoot ? "Root" : "Parent", UniqueId));
        RefreshDetails();
    }

    public OutputConnectorViewModel AddChildOutput(string name, string title)
    {
        var connector = new OutputConnectorViewModel(name, title, UniqueId);
        Output.Add(connector);
        return connector;
    }

    internal override void GenerateSockets()
    {
        // Behavior sockets are structural slots generated by the graph projection.
    }

    public void RefreshDetails()
    {
        Details = BuildDetails((AIbehaviorTreeNodeDefinition)Data);
    }

    protected override void UpdateTitle()
    {
        Title = FormatBehaviorNodeName(Data.GetType().Name);
        RefreshDetails();
    }

    private static Dictionary<string, string> BuildDetails(AIbehaviorTreeNodeDefinition node)
    {
        var details = new Dictionary<string, string>();

        switch (node)
        {
            case AIbehaviorSelectorTreeNodeDefinition selector:
                details["Rule"] = "First successful child";
                details["Children"] = selector.Children?.Count.ToString() ?? "0";
                break;
            case AIbehaviorSequenceTreeNodeDefinition sequence:
                details["Rule"] = "Ordered until failure";
                details["Children"] = sequence.Children?.Count.ToString() ?? "0";
                break;
            case AIbehaviorParallelNodeDefinition parallel:
                details["Rule"] = "Parallel branches";
                details["Children"] = parallel.Children?.Count.ToString() ?? "0";
                details["Wait For"] = parallel.WaitFor.ToString() ?? "";
                break;
            case AIbehaviorCompositeTreeNodeDefinition composite:
                details["Children"] = composite.Children?.Count.ToString() ?? "0";
                break;
            case AIbehaviorDecoratorNodeDefinition decorator:
                details["Child"] = GetHandleValue(decorator.Child)?.GetType().Name ?? "<empty>";
                break;
        }

        if (node is AIbehaviorTaskNodeDefinition taskNode)
        {
            AddTaskDetails(details, GetHandleValue(taskNode.Task));
        }

        if (node is AIbehaviorConditionNodeDefinition conditionNode)
        {
            AddConditionDetails(details, GetHandleValue(conditionNode.Condition));
            details["Failure"] = conditionNode.ResultIfFailed.ToString() ?? "";
        }

        if (node is AIbehaviorIfElseNodeDefinition ifElseNode)
        {
            AddExpressionSocketDetails(details, GetHandleValue(ifElseNode.Condition));
        }

        if (node is AIbehaviorFSMTreeNodeDefinition fsmNode)
        {
            details["States"] = fsmNode.States?.Count.ToString() ?? "0";
            details["Transitions"] = fsmNode.Transitions?.Count.ToString() ?? "0";
            details["Initial"] = GetStateIndex(fsmNode.States, GetHandleValue(fsmNode.InitialState)).ToString();
        }

        if (node is AIbehaviorFSMStateDefinition stateNode)
        {
            details["Initial"] = stateNode.IsInitial.ToString() ?? "";
            details["Exit"] = stateNode.IsExit.ToString() ?? "";
            details["Completion"] = stateNode.CompletionStatus.ToString() ?? "";
        }

        if (node is AIbehaviorRepeatNodeDefinition repeatNode)
        {
            details["Limit"] = GetMappingValue(GetHandleValue(repeatNode.Limit)) ?? "<empty>";
        }

        if (node is AIbehaviorSubtreeDefinition subtreeNode)
        {
            details["Tree"] = GetHandleValue(subtreeNode.Tree)?.TreeDefinition.DepotPath.GetResolvedText() ?? "<empty>";
        }

        if (node is AIbehaviorIncludedTreeDefinition includedNode)
        {
            var mapping = GetHandleValue(includedNode.TreeReference);
            details["Tree Arg"] = GetMappingValue(mapping) ?? "<empty>";
        }

        return details
            .Where(x => !string.IsNullOrWhiteSpace(x.Value))
            .ToDictionary(x => x.Key, x => x.Value);
    }

    private static void AddTaskDetails(IDictionary<string, string> details, RedBaseClass? task)
    {
        if (task == null)
        {
            details["Task"] = "<empty>";
            return;
        }

        details["Task"] = task.GetType().Name;

        if (task is AIbehaviorScriptTaskDefinition scriptTask)
        {
            AddScriptDetails(details, GetHandleValue(scriptTask.Script));
        }
        else if (task is AIbehaviorStackScriptTaskDefinition stackTask)
        {
            AddScriptDetails(details, GetHandleValue(stackTask.Script));
        }
    }

    private static void AddConditionDetails(IDictionary<string, string> details, RedBaseClass? condition)
    {
        if (condition == null)
        {
            details["Condition"] = "<empty>";
            return;
        }

        details["Condition"] = condition.GetType().Name;

        if (condition is AIbehaviorScriptConditionDefinition scriptCondition)
        {
            AddScriptDetails(details, GetHandleValue(scriptCondition.Script));
        }
        else if (condition is AIbehaviorMappingConditionDefinition mappingCondition)
        {
            details["Mapping"] = GetMappingValue(GetHandleValue(mappingCondition.Value)) ?? "<empty>";
        }
    }

    private static void AddExpressionSocketDetails(IDictionary<string, string> details, AIbehaviorExpressionSocket? socket)
    {
        if (socket == null)
        {
            details["Expression"] = "<empty>";
            return;
        }

        var expression = GetHandleValue(socket.Expression);
        details["Expression"] = expression?.GetType().Name ?? "<empty>";

        if (expression is AIbehaviorScriptPassiveExpressionDefinition scriptExpression)
        {
            AddScriptDetails(details, GetHandleValue(scriptExpression.Script));
        }
        else if (expression is AIbehaviorMappingExpressionDefinition mappingExpression)
        {
            details["Mapping"] = GetMappingValue(GetHandleValue(mappingExpression.Mapping)) ?? "<empty>";
        }
    }

    private static void AddScriptDetails(IDictionary<string, string> details, RedBaseClass? script)
    {
        if (script == null)
        {
            details["Script"] = "<empty>";
            return;
        }

        details["Script"] = script.GetType().Name;

        switch (script)
        {
            case CustomEventCondition customEventCondition:
                AddFormattedDetail(details, "Event", customEventCondition.EventName);
                break;
            case TweakAIActionSelector selector:
                AddFormattedDetail(details, "Selector", selector.Selector);
                break;
            case TweakAIActionSmartComposite smartComposite:
                AddFormattedDetail(details, "Smart Composite", smartComposite.SmartComposite);
                break;
            case TweakAIAction tweakAction:
                AddFormattedDetail(details, "Record", tweakAction.Record);
                break;
            case TweakAIActionCondition tweakCondition:
                AddFormattedDetail(details, "Record", tweakCondition.Record);
                break;
            case AIAnimationTask animationTask:
                AddFormattedDetail(details, "Record", animationTask.Record);
                break;
        }
    }

    private static void AddFormattedDetail(IDictionary<string, string> details, string label, IRedType? value)
    {
        if (details.ContainsKey(label))
        {
            return;
        }

        var formattedValue = FormatRedValue(value);
        if (!string.IsNullOrWhiteSpace(formattedValue))
        {
            details[label] = formattedValue;
        }
    }

    private static int GetStateIndex(CArray<CHandle<AIbehaviorFSMStateDefinition>>? states, AIbehaviorFSMStateDefinition? state)
    {
        if (states == null || state == null)
        {
            return -1;
        }

        for (var i = 0; i < states.Count; i++)
        {
            if (ReferenceEquals(GetHandleValue(states[i]), state))
            {
                return i;
            }
        }

        return -1;
    }

    private static string? GetMappingValue(AIArgumentMapping? mapping)
    {
        var value = mapping?.DefaultValue.Value;
        return FormatRedValue(value);
    }

    private static string? FormatRedValue(IRedType? value)
    {
        return value switch
        {
            CName cname => cname.GetResolvedText(),
            TweakDBID tweakDBID when tweakDBID == TweakDBID.Empty => null,
            TweakDBID tweakDBID => tweakDBID.TryGetResolvedText(out var resolved) ? resolved : ((ulong)tweakDBID).ToString(),
            IRedBaseHandle handle => handle.GetValue()?.GetType().Name,
            RedBaseClass redBaseClass => redBaseClass.GetType().Name,
            null => null,
            _ => value.ToString()
        };
    }

    private static T? GetHandleValue<T>(CHandle<T>? handle) where T : RedBaseClass => handle?.GetValue() as T;

    private static string FormatBehaviorNodeName(string typeName)
    {
        if (typeName.StartsWith("AIbehavior", StringComparison.Ordinal))
        {
            typeName = typeName["AIbehavior".Length..];
        }

        if (typeName.EndsWith("TreeNodeDefinition", StringComparison.Ordinal))
        {
            typeName = typeName[..^"TreeNodeDefinition".Length];
        }
        else if (typeName.EndsWith("NodeDefinition", StringComparison.Ordinal))
        {
            typeName = typeName[..^"NodeDefinition".Length];
        }
        else if (typeName.EndsWith("Definition", StringComparison.Ordinal))
        {
            typeName = typeName[..^"Definition".Length];
        }

        return typeName switch
        {
            "FSMTree" => "FSM",
            "FSMState" => "FSM State",
            "Subtree" => "Subtree",
            "IncludedTree" => "Included Tree",
            _ => typeName
        };
    }

    private static Brush GetBackgroundForNode(AIbehaviorTreeNodeDefinition node)
    {
        var color = node switch
        {
            AIbehaviorFSMTreeNodeDefinition => "#663E6177",
            AIbehaviorFSMStateDefinition => "#66406055",
            AIbehaviorSelectorTreeNodeDefinition => "#66535A40",
            AIbehaviorSequenceTreeNodeDefinition => "#66474F5F",
            AIbehaviorParallelNodeDefinition => "#66513F63",
            AIbehaviorCompositeTreeNodeDefinition => "#66454B55",
            AIbehaviorConditionNodeDefinition => "#6633546F",
            AIbehaviorTaskNodeDefinition => "#66563F74",
            AIbehaviorNestedTreeDefinition => "#66456849",
            AIbehaviorSucceederNodeDefinition or AIbehaviorFailerNodeDefinition => "#66594E38",
            AIbehaviorLeafTreeNodeDefinition => "#66474747",
            _ => "#664A4A4A"
        };

        return new SolidColorBrush((Color)ColorConverter.ConvertFromString(color));
    }

    private static Brush GetContentBackgroundForNode(AIbehaviorTreeNodeDefinition node)
    {
        var color = node switch
        {
            AIbehaviorFSMTreeNodeDefinition => "#333E6177",
            AIbehaviorFSMStateDefinition => "#33406055",
            AIbehaviorSelectorTreeNodeDefinition => "#33535A40",
            AIbehaviorSequenceTreeNodeDefinition => "#33474F5F",
            AIbehaviorParallelNodeDefinition => "#33513F63",
            AIbehaviorCompositeTreeNodeDefinition => "#33454B55",
            AIbehaviorConditionNodeDefinition => "#3333546F",
            AIbehaviorTaskNodeDefinition => "#33563F74",
            AIbehaviorNestedTreeDefinition => "#33456849",
            AIbehaviorSucceederNodeDefinition or AIbehaviorFailerNodeDefinition => "#33594E38",
            AIbehaviorLeafTreeNodeDefinition => "#33474747",
            _ => "#334A4A4A"
        };

        return new SolidColorBrush((Color)ColorConverter.ConvertFromString(color));
    }
}
