#pragma once

#pragma unmanaged
#pragma warning(disable: 4635)
#pragma warning(push, 3)
#include "irrlicht.h"
#pragma warning(pop)
#pragma warning(default: 4635)
#pragma managed

#include "Lime.h"

// enums
#include "AlphaSource.h"
#include "AnimatedMeshType.h"
#include "AnimationTypeMD2.h"
#include "AntiAliasingMode.h"
#include "AttributeReadWriteFlag.h"
#include "AttributeType.h"
#include "BlendFactor.h"
#include "BlendOperation.h"
#include "BoneAnimationMode.h"
#include "BoneSkinningSpace.h"
#include "ClearBufferFlag.h"
#include "ColorFormat.h"
#include "ColorMaterial.h"
#include "ColorPlane.h"
#include "ComparisonFunc.h"
#include "CullingType.h"
#include "CursorPlatformBehavior.h"
#include "DebugSceneType.h"
#include "DeviceType.h"
#include "DriverType.h"
#include "EventType.h"
#include "FileArchiveType.h"
#include "FileSystemType.h"
#include "FogType.h"
#include "GeometryShaderType.h"
#include "GPUShadingLanguage.h"
#include "GUIAlignment.h"
#include "GUIButtonState.h"
#include "GUIColumnOrdering.h"
#include "GUIContextMenuClose.h"
#include "GUIDefaultColor.h"
#include "GUIDefaultFont.h"
#include "GUIDefaultIcon.h"
#include "GUIDefaultSize.h"
#include "GUIDefaultText.h"
#include "GUIElementType.h"
#include "GUIEventType.h"
#include "GUIFontType.h"
#include "GUIListBoxColor.h"
#include "GUIMessageBoxFlag.h"
#include "GUIOrderingMode.h"
#include "GUISkinType.h"
#include "GUISpinBoxValidation.h"
#include "GUITableDrawFlag.h"
#include "HardwareBufferType.h"
#include "HardwareMappingHint.h"
#include "IndexType.h"
#include "InterpolationMode.h"
#include "JointUpdateOnRender.h"
#include "KeyAction.h"
#include "KeyCode.h"
#include "LightType.h"
#include "LogLevel.h"
#include "MaterialFlag.h"
#include "MaterialType.h"
#include "ModulateFunc.h"
#include "MouseEventType.h"
#include "ParticleAffectorType.h"
#include "ParticleEmitterType.h"
#include "PixelShaderType.h"
#include "PrimitiveType.h"
#include "RenderTarget.h"
#include "SceneNodeAnimatorType.h"
#include "SceneNodeRenderPass.h"
#include "SceneNodeType.h"
#include "SceneParameters.h" // string enum (e.g. abstract sealed class with static getters)
#include "TerrainPatchSize.h"
#include "TextureClamp.h"
#include "TextureCreationFlag.h"
#include "TextureLockMode.h"
#include "TransformationState.h"
#include "VertexShaderType.h"
#include "VertexType.h"
#include "VideoDriverFeature.h"
#include "VideoModeAspectRatio.h"

// basic types
#include "Vector.h" // must be before AABBox.h
#include "Line.h" // must be before AABBox.h
#include "AABBox.h"
#include "Color.h"
#include "Dimension.h"
#include "Rect.h" // must be before Matrix.h
#include "Plane.h" // must be before Matrix.h
#include "Matrix.h"
#include "Quaternion.h"
#include "Triangle.h"
#include "Vertex.h"

// other header-only types
#include "AttributeReadWriteOptions.h"
#include "ExposedVideoData.h"
#include "Fog.h"
#include "KeyMap.h"
#include "NamedPath.h"
#include "VideoMode.h"
#include "ViewFrustum.h"

// inheritors
#include "EventReceiverInheritor.h"
#include "GUIElementInheritor.h"
#include "SceneNodeInheritor.h"
#include "ShaderCallBackInheritor.h"
