using System.IO;
using CP77.CR2W.Reflection;
using FastMember;
using static CP77.CR2W.Types.Enums;

namespace CP77.CR2W.Types
{
	[REDMeta]
	public class animSermoTestController : CVariable
	{
		[Ordinal(0)]  [RED("faceEnvelope")] public CFloat FaceEnvelope { get; set; }
		[Ordinal(1)]  [RED("upperFace")] public CFloat UpperFace { get; set; }
		[Ordinal(2)]  [RED("lowerFace")] public CFloat LowerFace { get; set; }
		[Ordinal(3)]  [RED("lipSyncEnvelope")] public CFloat LipSyncEnvelope { get; set; }
		[Ordinal(4)]  [RED("lipSyncLeftEnvelope")] public CFloat LipSyncLeftEnvelope { get; set; }
		[Ordinal(5)]  [RED("lipSyncRightEnvelope")] public CFloat LipSyncRightEnvelope { get; set; }
		[Ordinal(6)]  [RED("jaliJaw")] public CFloat JaliJaw { get; set; }
		[Ordinal(7)]  [RED("jaliLips")] public CFloat JaliLips { get; set; }
		[Ordinal(8)]  [RED("muzzleLips")] public CFloat MuzzleLips { get; set; }
		[Ordinal(9)]  [RED("muzzleEyes")] public CFloat MuzzleEyes { get; set; }
		[Ordinal(10)]  [RED("muzzleBrows")] public CFloat MuzzleBrows { get; set; }
		[Ordinal(11)]  [RED("muzzleEyeDirections")] public CFloat MuzzleEyeDirections { get; set; }
		[Ordinal(12)]  [RED("eye_l_brows_raise_in")] public CFloat Eye_l_brows_raise_in { get; set; }
		[Ordinal(13)]  [RED("eye_r_brows_raise_in")] public CFloat Eye_r_brows_raise_in { get; set; }
		[Ordinal(14)]  [RED("eye_l_brows_raise_out")] public CFloat Eye_l_brows_raise_out { get; set; }
		[Ordinal(15)]  [RED("eye_r_brows_raise_out")] public CFloat Eye_r_brows_raise_out { get; set; }
		[Ordinal(16)]  [RED("eye_l_brows_lower")] public CFloat Eye_l_brows_lower { get; set; }
		[Ordinal(17)]  [RED("eye_r_brows_lower")] public CFloat Eye_r_brows_lower { get; set; }
		[Ordinal(18)]  [RED("eye_l_brows_lateral")] public CFloat Eye_l_brows_lateral { get; set; }
		[Ordinal(19)]  [RED("eye_r_brows_lateral")] public CFloat Eye_r_brows_lateral { get; set; }
		[Ordinal(20)]  [RED("eye_l_blink")] public CFloat Eye_l_blink { get; set; }
		[Ordinal(21)]  [RED("eye_r_blink")] public CFloat Eye_r_blink { get; set; }
		[Ordinal(22)]  [RED("eye_l_widen")] public CFloat Eye_l_widen { get; set; }
		[Ordinal(23)]  [RED("eye_r_widen")] public CFloat Eye_r_widen { get; set; }
		[Ordinal(24)]  [RED("eye_l_oculi_squint_inner")] public CFloat Eye_l_oculi_squint_inner { get; set; }
		[Ordinal(25)]  [RED("eye_r_oculi_squint_inner")] public CFloat Eye_r_oculi_squint_inner { get; set; }
		[Ordinal(26)]  [RED("eye_l_oculi_squint_outer_lower")] public CFloat Eye_l_oculi_squint_outer_lower { get; set; }
		[Ordinal(27)]  [RED("eye_r_oculi_squint_outer_lower")] public CFloat Eye_r_oculi_squint_outer_lower { get; set; }
		[Ordinal(28)]  [RED("eye_l_oculi_squint_outer_upper")] public CFloat Eye_l_oculi_squint_outer_upper { get; set; }
		[Ordinal(29)]  [RED("eye_r_oculi_squint_outer_upper")] public CFloat Eye_r_oculi_squint_outer_upper { get; set; }
		[Ordinal(30)]  [RED("nose_l_compress")] public CFloat Nose_l_compress { get; set; }
		[Ordinal(31)]  [RED("nose_r_compress")] public CFloat Nose_r_compress { get; set; }
		[Ordinal(32)]  [RED("nose_l_breathe_in")] public CFloat Nose_l_breathe_in { get; set; }
		[Ordinal(33)]  [RED("nose_r_breathe_in")] public CFloat Nose_r_breathe_in { get; set; }
		[Ordinal(34)]  [RED("nose_l_breathe_out")] public CFloat Nose_l_breathe_out { get; set; }
		[Ordinal(35)]  [RED("nose_r_breathe_out")] public CFloat Nose_r_breathe_out { get; set; }
		[Ordinal(36)]  [RED("nose_l_snear")] public CFloat Nose_l_snear { get; set; }
		[Ordinal(37)]  [RED("nose_r_snear")] public CFloat Nose_r_snear { get; set; }
		[Ordinal(38)]  [RED("lips_l_nasolabialDeepener")] public CFloat Lips_l_nasolabialDeepener { get; set; }
		[Ordinal(39)]  [RED("lips_r_nasolabialDeepener")] public CFloat Lips_r_nasolabialDeepener { get; set; }
		[Ordinal(40)]  [RED("lips_l_upper_raise")] public CFloat Lips_l_upper_raise { get; set; }
		[Ordinal(41)]  [RED("lips_r_upper_raise")] public CFloat Lips_r_upper_raise { get; set; }
		[Ordinal(42)]  [RED("lips_l_pull")] public CFloat Lips_l_pull { get; set; }
		[Ordinal(43)]  [RED("lips_r_pull")] public CFloat Lips_r_pull { get; set; }
		[Ordinal(44)]  [RED("lips_l_corner_up")] public CFloat Lips_l_corner_up { get; set; }
		[Ordinal(45)]  [RED("lips_r_corner_up")] public CFloat Lips_r_corner_up { get; set; }
		[Ordinal(46)]  [RED("lips_l_corner_wide")] public CFloat Lips_l_corner_wide { get; set; }
		[Ordinal(47)]  [RED("lips_r_corner_wide")] public CFloat Lips_r_corner_wide { get; set; }
		[Ordinal(48)]  [RED("lips_l_corner_stretch")] public CFloat Lips_l_corner_stretch { get; set; }
		[Ordinal(49)]  [RED("lips_r_corner_stretch")] public CFloat Lips_r_corner_stretch { get; set; }
		[Ordinal(50)]  [RED("lips_l_stretch")] public CFloat Lips_l_stretch { get; set; }
		[Ordinal(51)]  [RED("lips_r_stretch")] public CFloat Lips_r_stretch { get; set; }
		[Ordinal(52)]  [RED("lips_l_corner_sharp_up")] public CFloat Lips_l_corner_sharp_up { get; set; }
		[Ordinal(53)]  [RED("lips_r_corner_sharp_up")] public CFloat Lips_r_corner_sharp_up { get; set; }
		[Ordinal(54)]  [RED("lips_suck_up")] public CFloat Lips_suck_up { get; set; }
		[Ordinal(55)]  [RED("lips_suck_dn")] public CFloat Lips_suck_dn { get; set; }
		[Ordinal(56)]  [RED("lips_puff_up")] public CFloat Lips_puff_up { get; set; }
		[Ordinal(57)]  [RED("lips_puff_dn")] public CFloat Lips_puff_dn { get; set; }
		[Ordinal(58)]  [RED("lips_apart_up")] public CFloat Lips_apart_up { get; set; }
		[Ordinal(59)]  [RED("lips_apart_dn")] public CFloat Lips_apart_dn { get; set; }
		[Ordinal(60)]  [RED("lips_l_lower_raise")] public CFloat Lips_l_lower_raise { get; set; }
		[Ordinal(61)]  [RED("lips_r_lower_raise")] public CFloat Lips_r_lower_raise { get; set; }
		[Ordinal(62)]  [RED("lips_l_corner_dn")] public CFloat Lips_l_corner_dn { get; set; }
		[Ordinal(63)]  [RED("lips_r_corner_dn")] public CFloat Lips_r_corner_dn { get; set; }
		[Ordinal(64)]  [RED("lips_chin_raise")] public CFloat Lips_chin_raise { get; set; }
		[Ordinal(65)]  [RED("lips_together_up")] public CFloat Lips_together_up { get; set; }
		[Ordinal(66)]  [RED("lips_together_dn")] public CFloat Lips_together_dn { get; set; }
		[Ordinal(67)]  [RED("lips_l_purse")] public CFloat Lips_l_purse { get; set; }
		[Ordinal(68)]  [RED("lips_r_purse")] public CFloat Lips_r_purse { get; set; }
		[Ordinal(69)]  [RED("lips_l_funnel")] public CFloat Lips_l_funnel { get; set; }
		[Ordinal(70)]  [RED("lips_r_funnel")] public CFloat Lips_r_funnel { get; set; }
		[Ordinal(71)]  [RED("lips_tighten_up")] public CFloat Lips_tighten_up { get; set; }
		[Ordinal(72)]  [RED("lips_tighten_dn")] public CFloat Lips_tighten_dn { get; set; }
		[Ordinal(73)]  [RED("lips_mid_shift_l")] public CFloat Lips_mid_shift_l { get; set; }
		[Ordinal(74)]  [RED("lips_mid_shift_r")] public CFloat Lips_mid_shift_r { get; set; }
		[Ordinal(75)]  [RED("lips_mid_shift_up")] public CFloat Lips_mid_shift_up { get; set; }
		[Ordinal(76)]  [RED("lips_mid_shift_dn")] public CFloat Lips_mid_shift_dn { get; set; }
		[Ordinal(77)]  [RED("cheek_l_suck")] public CFloat Cheek_l_suck { get; set; }
		[Ordinal(78)]  [RED("cheek_r_suck")] public CFloat Cheek_r_suck { get; set; }
		[Ordinal(79)]  [RED("cheek_l_puff")] public CFloat Cheek_l_puff { get; set; }
		[Ordinal(80)]  [RED("cheek_r_puff")] public CFloat Cheek_r_puff { get; set; }
		[Ordinal(81)]  [RED("jaw_mid_open")] public CFloat Jaw_mid_open { get; set; }
		[Ordinal(82)]  [RED("jaw_mid_close")] public CFloat Jaw_mid_close { get; set; }
		[Ordinal(83)]  [RED("jaw_mid_shift_l")] public CFloat Jaw_mid_shift_l { get; set; }
		[Ordinal(84)]  [RED("jaw_mid_shift_r")] public CFloat Jaw_mid_shift_r { get; set; }
		[Ordinal(85)]  [RED("jaw_mid_shift_fwd")] public CFloat Jaw_mid_shift_fwd { get; set; }
		[Ordinal(86)]  [RED("jaw_mid_shift_back")] public CFloat Jaw_mid_shift_back { get; set; }
		[Ordinal(87)]  [RED("jaw_mid_clench")] public CFloat Jaw_mid_clench { get; set; }
		[Ordinal(88)]  [RED("neck_l_stretch")] public CFloat Neck_l_stretch { get; set; }
		[Ordinal(89)]  [RED("neck_r_stretch")] public CFloat Neck_r_stretch { get; set; }
		[Ordinal(90)]  [RED("neck_tighten")] public CFloat Neck_tighten { get; set; }
		[Ordinal(91)]  [RED("neck_l_sternocleidomastoid_flex")] public CFloat Neck_l_sternocleidomastoid_flex { get; set; }
		[Ordinal(92)]  [RED("neck_r_sternocleidomastoid_flex")] public CFloat Neck_r_sternocleidomastoid_flex { get; set; }
		[Ordinal(93)]  [RED("neck_l_platysma_flex")] public CFloat Neck_l_platysma_flex { get; set; }
		[Ordinal(94)]  [RED("neck_r_platysma_flex")] public CFloat Neck_r_platysma_flex { get; set; }
		[Ordinal(95)]  [RED("neck_throat_adamsApple_up")] public CFloat Neck_throat_adamsApple_up { get; set; }
		[Ordinal(96)]  [RED("neck_throat_adamsApple_dn")] public CFloat Neck_throat_adamsApple_dn { get; set; }
		[Ordinal(97)]  [RED("neck_throat_compress")] public CFloat Neck_throat_compress { get; set; }
		[Ordinal(98)]  [RED("neck_throat_open")] public CFloat Neck_throat_open { get; set; }
		[Ordinal(99)]  [RED("neck_l_turn")] public CFloat Neck_l_turn { get; set; }
		[Ordinal(100)]  [RED("neck_r_turn")] public CFloat Neck_r_turn { get; set; }
		[Ordinal(101)]  [RED("neck_up_turn")] public CFloat Neck_up_turn { get; set; }
		[Ordinal(102)]  [RED("neck_dn_turn")] public CFloat Neck_dn_turn { get; set; }
		[Ordinal(103)]  [RED("neck_l_tilt")] public CFloat Neck_l_tilt { get; set; }
		[Ordinal(104)]  [RED("neck_r_tilt")] public CFloat Neck_r_tilt { get; set; }
		[Ordinal(105)]  [RED("head_neck_up_turn")] public CFloat Head_neck_up_turn { get; set; }
		[Ordinal(106)]  [RED("head_neck_dn_turn")] public CFloat Head_neck_dn_turn { get; set; }
		[Ordinal(107)]  [RED("head_neck_l_tilt")] public CFloat Head_neck_l_tilt { get; set; }
		[Ordinal(108)]  [RED("head_neck_r_tilt")] public CFloat Head_neck_r_tilt { get; set; }
		[Ordinal(109)]  [RED("ear_l_shift_up")] public CFloat Ear_l_shift_up { get; set; }
		[Ordinal(110)]  [RED("ear_r_shift_up")] public CFloat Ear_r_shift_up { get; set; }
		[Ordinal(111)]  [RED("sculp_mid_slide")] public CFloat Sculp_mid_slide { get; set; }
		[Ordinal(112)]  [RED("eye_l_dir_up")] public CFloat Eye_l_dir_up { get; set; }
		[Ordinal(113)]  [RED("eye_l_dir_dn")] public CFloat Eye_l_dir_dn { get; set; }
		[Ordinal(114)]  [RED("eye_l_dir_in")] public CFloat Eye_l_dir_in { get; set; }
		[Ordinal(115)]  [RED("eye_l_dir_out")] public CFloat Eye_l_dir_out { get; set; }
		[Ordinal(116)]  [RED("eye_r_dir_up")] public CFloat Eye_r_dir_up { get; set; }
		[Ordinal(117)]  [RED("eye_r_dir_dn")] public CFloat Eye_r_dir_dn { get; set; }
		[Ordinal(118)]  [RED("eye_r_dir_in")] public CFloat Eye_r_dir_in { get; set; }
		[Ordinal(119)]  [RED("eye_r_dir_out")] public CFloat Eye_r_dir_out { get; set; }
		[Ordinal(120)]  [RED("face_gravity_fwd")] public CFloat Face_gravity_fwd { get; set; }
		[Ordinal(121)]  [RED("face_gravity_back")] public CFloat Face_gravity_back { get; set; }
		[Ordinal(122)]  [RED("face_gravity_l")] public CFloat Face_gravity_l { get; set; }
		[Ordinal(123)]  [RED("face_gravity_r")] public CFloat Face_gravity_r { get; set; }
		[Ordinal(124)]  [RED("lips_corner_sticky")] public CFloat Lips_corner_sticky { get; set; }
		[Ordinal(125)]  [RED("lips_l_corner_up_in_sticky_cutScene")] public CFloat Lips_l_corner_up_in_sticky_cutScene { get; set; }
		[Ordinal(126)]  [RED("lips_l_corner_dn_in_sticky_cutScene")] public CFloat Lips_l_corner_dn_in_sticky_cutScene { get; set; }
		[Ordinal(127)]  [RED("lips_l_corner_up_out_sticky_cutScene")] public CFloat Lips_l_corner_up_out_sticky_cutScene { get; set; }
		[Ordinal(128)]  [RED("lips_l_corner_dn_out_sticky_cutScene")] public CFloat Lips_l_corner_dn_out_sticky_cutScene { get; set; }
		[Ordinal(129)]  [RED("lips_r_corner_up_in_sticky_cutScene")] public CFloat Lips_r_corner_up_in_sticky_cutScene { get; set; }
		[Ordinal(130)]  [RED("lips_r_corner_up_out_sticky_cutScene")] public CFloat Lips_r_corner_up_out_sticky_cutScene { get; set; }
		[Ordinal(131)]  [RED("lips_r_corner_dn_in_sticky_cutScene")] public CFloat Lips_r_corner_dn_in_sticky_cutScene { get; set; }
		[Ordinal(132)]  [RED("lips_r_corner_dn_out_sticky_cutScene")] public CFloat Lips_r_corner_dn_out_sticky_cutScene { get; set; }
		[Ordinal(133)]  [RED("eye_l_pupil_narrow")] public CFloat Eye_l_pupil_narrow { get; set; }
		[Ordinal(134)]  [RED("eye_r_pupil_narrow")] public CFloat Eye_r_pupil_narrow { get; set; }
		[Ordinal(135)]  [RED("eye_l_pupil_wide")] public CFloat Eye_l_pupil_wide { get; set; }
		[Ordinal(136)]  [RED("eye_r_pupil_wide")] public CFloat Eye_r_pupil_wide { get; set; }
		[Ordinal(137)]  [RED("tongue_mid_base_l")] public CFloat Tongue_mid_base_l { get; set; }
		[Ordinal(138)]  [RED("tongue_mid_base_r")] public CFloat Tongue_mid_base_r { get; set; }
		[Ordinal(139)]  [RED("tongue_mid_base_dn")] public CFloat Tongue_mid_base_dn { get; set; }
		[Ordinal(140)]  [RED("tongue_mid_base_up")] public CFloat Tongue_mid_base_up { get; set; }
		[Ordinal(141)]  [RED("tongue_mid_base_fwd")] public CFloat Tongue_mid_base_fwd { get; set; }
		[Ordinal(142)]  [RED("tongue_mid_base_front")] public CFloat Tongue_mid_base_front { get; set; }
		[Ordinal(143)]  [RED("tongue_mid_base_back")] public CFloat Tongue_mid_base_back { get; set; }
		[Ordinal(144)]  [RED("tongue_mid_fwd")] public CFloat Tongue_mid_fwd { get; set; }
		[Ordinal(145)]  [RED("tongue_mid_lift")] public CFloat Tongue_mid_lift { get; set; }
		[Ordinal(146)]  [RED("tongue_mid_tip_l")] public CFloat Tongue_mid_tip_l { get; set; }
		[Ordinal(147)]  [RED("tongue_mid_tip_r")] public CFloat Tongue_mid_tip_r { get; set; }
		[Ordinal(148)]  [RED("tongue_mid_tip_dn")] public CFloat Tongue_mid_tip_dn { get; set; }
		[Ordinal(149)]  [RED("tongue_mid_tip_up")] public CFloat Tongue_mid_tip_up { get; set; }
		[Ordinal(150)]  [RED("tongue_mid_twist_l")] public CFloat Tongue_mid_twist_l { get; set; }
		[Ordinal(151)]  [RED("tongue_mid_twist_r")] public CFloat Tongue_mid_twist_r { get; set; }
		[Ordinal(152)]  [RED("tongue_mid_thick")] public CFloat Tongue_mid_thick { get; set; }
		[Ordinal(153)]  [RED("nose_l_snearAnimOverrideWeight")] public CFloat Nose_l_snearAnimOverrideWeight { get; set; }
		[Ordinal(154)]  [RED("nose_r_snearAnimOverrideWeight")] public CFloat Nose_r_snearAnimOverrideWeight { get; set; }
		[Ordinal(155)]  [RED("lips_l_nasolabialDeepenerAnimOverrideWeight")] public CFloat Lips_l_nasolabialDeepenerAnimOverrideWeight { get; set; }
		[Ordinal(156)]  [RED("lips_r_nasolabialDeepenerAnimOverrideWeight")] public CFloat Lips_r_nasolabialDeepenerAnimOverrideWeight { get; set; }
		[Ordinal(157)]  [RED("lips_l_upper_raiseAnimOverrideWeight")] public CFloat Lips_l_upper_raiseAnimOverrideWeight { get; set; }
		[Ordinal(158)]  [RED("lips_r_upper_raiseAnimOverrideWeight")] public CFloat Lips_r_upper_raiseAnimOverrideWeight { get; set; }
		[Ordinal(159)]  [RED("lips_l_pullAnimOverrideWeight")] public CFloat Lips_l_pullAnimOverrideWeight { get; set; }
		[Ordinal(160)]  [RED("lips_r_pullAnimOverrideWeight")] public CFloat Lips_r_pullAnimOverrideWeight { get; set; }
		[Ordinal(161)]  [RED("lips_l_corner_upAnimOverrideWeight")] public CFloat Lips_l_corner_upAnimOverrideWeight { get; set; }
		[Ordinal(162)]  [RED("lips_r_corner_upAnimOverrideWeight")] public CFloat Lips_r_corner_upAnimOverrideWeight { get; set; }
		[Ordinal(163)]  [RED("lips_l_corner_wideAnimOverrideWeight")] public CFloat Lips_l_corner_wideAnimOverrideWeight { get; set; }
		[Ordinal(164)]  [RED("lips_r_corner_wideAnimOverrideWeight")] public CFloat Lips_r_corner_wideAnimOverrideWeight { get; set; }
		[Ordinal(165)]  [RED("lips_l_corner_stretchAnimOverrideWeight")] public CFloat Lips_l_corner_stretchAnimOverrideWeight { get; set; }
		[Ordinal(166)]  [RED("lips_r_corner_stretchAnimOverrideWeight")] public CFloat Lips_r_corner_stretchAnimOverrideWeight { get; set; }
		[Ordinal(167)]  [RED("lips_l_stretchAnimOverrideWeight")] public CFloat Lips_l_stretchAnimOverrideWeight { get; set; }
		[Ordinal(168)]  [RED("lips_r_stretchAnimOverrideWeight")] public CFloat Lips_r_stretchAnimOverrideWeight { get; set; }
		[Ordinal(169)]  [RED("lips_l_corner_sharp_upAnimOverrideWeight")] public CFloat Lips_l_corner_sharp_upAnimOverrideWeight { get; set; }
		[Ordinal(170)]  [RED("lips_r_corner_sharp_upAnimOverrideWeight")] public CFloat Lips_r_corner_sharp_upAnimOverrideWeight { get; set; }
		[Ordinal(171)]  [RED("lips_suck_upAnimOverrideWeight")] public CFloat Lips_suck_upAnimOverrideWeight { get; set; }
		[Ordinal(172)]  [RED("lips_suck_dnAnimOverrideWeight")] public CFloat Lips_suck_dnAnimOverrideWeight { get; set; }
		[Ordinal(173)]  [RED("lips_puff_upAnimOverrideWeight")] public CFloat Lips_puff_upAnimOverrideWeight { get; set; }
		[Ordinal(174)]  [RED("lips_puff_dnAnimOverrideWeight")] public CFloat Lips_puff_dnAnimOverrideWeight { get; set; }
		[Ordinal(175)]  [RED("lips_apart_upAnimOverrideWeight")] public CFloat Lips_apart_upAnimOverrideWeight { get; set; }
		[Ordinal(176)]  [RED("lips_apart_dnAnimOverrideWeight")] public CFloat Lips_apart_dnAnimOverrideWeight { get; set; }
		[Ordinal(177)]  [RED("lips_l_lower_raiseAnimOverrideWeight")] public CFloat Lips_l_lower_raiseAnimOverrideWeight { get; set; }
		[Ordinal(178)]  [RED("lips_r_lower_raiseAnimOverrideWeight")] public CFloat Lips_r_lower_raiseAnimOverrideWeight { get; set; }
		[Ordinal(179)]  [RED("lips_l_corner_dnAnimOverrideWeight")] public CFloat Lips_l_corner_dnAnimOverrideWeight { get; set; }
		[Ordinal(180)]  [RED("lips_r_corner_dnAnimOverrideWeight")] public CFloat Lips_r_corner_dnAnimOverrideWeight { get; set; }
		[Ordinal(181)]  [RED("lips_chin_raiseAnimOverrideWeight")] public CFloat Lips_chin_raiseAnimOverrideWeight { get; set; }
		[Ordinal(182)]  [RED("lips_together_upAnimOverrideWeight")] public CFloat Lips_together_upAnimOverrideWeight { get; set; }
		[Ordinal(183)]  [RED("lips_together_dnAnimOverrideWeight")] public CFloat Lips_together_dnAnimOverrideWeight { get; set; }
		[Ordinal(184)]  [RED("lips_l_purseAnimOverrideWeight")] public CFloat Lips_l_purseAnimOverrideWeight { get; set; }
		[Ordinal(185)]  [RED("lips_r_purseAnimOverrideWeight")] public CFloat Lips_r_purseAnimOverrideWeight { get; set; }
		[Ordinal(186)]  [RED("lips_l_funnelAnimOverrideWeight")] public CFloat Lips_l_funnelAnimOverrideWeight { get; set; }
		[Ordinal(187)]  [RED("lips_r_funnelAnimOverrideWeight")] public CFloat Lips_r_funnelAnimOverrideWeight { get; set; }
		[Ordinal(188)]  [RED("lips_tighten_upAnimOverrideWeight")] public CFloat Lips_tighten_upAnimOverrideWeight { get; set; }
		[Ordinal(189)]  [RED("lips_tighten_dnAnimOverrideWeight")] public CFloat Lips_tighten_dnAnimOverrideWeight { get; set; }
		[Ordinal(190)]  [RED("lips_mid_shift_lAnimOverrideWeight")] public CFloat Lips_mid_shift_lAnimOverrideWeight { get; set; }
		[Ordinal(191)]  [RED("lips_mid_shift_rAnimOverrideWeight")] public CFloat Lips_mid_shift_rAnimOverrideWeight { get; set; }
		[Ordinal(192)]  [RED("lips_mid_shift_upAnimOverrideWeight")] public CFloat Lips_mid_shift_upAnimOverrideWeight { get; set; }
		[Ordinal(193)]  [RED("lips_mid_shift_dnAnimOverrideWeight")] public CFloat Lips_mid_shift_dnAnimOverrideWeight { get; set; }
		[Ordinal(194)]  [RED("cheek_l_puffAnimOverrideWeight")] public CFloat Cheek_l_puffAnimOverrideWeight { get; set; }
		[Ordinal(195)]  [RED("cheek_r_puffAnimOverrideWeight")] public CFloat Cheek_r_puffAnimOverrideWeight { get; set; }
		[Ordinal(196)]  [RED("jaw_mid_openAnimOverrideWeight")] public CFloat Jaw_mid_openAnimOverrideWeight { get; set; }
		[Ordinal(197)]  [RED("jaw_mid_closeAnimOverrideWeight")] public CFloat Jaw_mid_closeAnimOverrideWeight { get; set; }
		[Ordinal(198)]  [RED("jaw_mid_shift_lAnimOverrideWeight")] public CFloat Jaw_mid_shift_lAnimOverrideWeight { get; set; }
		[Ordinal(199)]  [RED("jaw_mid_shift_rAnimOverrideWeight")] public CFloat Jaw_mid_shift_rAnimOverrideWeight { get; set; }
		[Ordinal(200)]  [RED("jaw_mid_shift_fwdAnimOverrideWeight")] public CFloat Jaw_mid_shift_fwdAnimOverrideWeight { get; set; }
		[Ordinal(201)]  [RED("jaw_mid_shift_backAnimOverrideWeight")] public CFloat Jaw_mid_shift_backAnimOverrideWeight { get; set; }
		[Ordinal(202)]  [RED("jaw_mid_clenchAnimOverrideWeight")] public CFloat Jaw_mid_clenchAnimOverrideWeight { get; set; }
		[Ordinal(203)]  [RED("neck_l_stretchAnimOverrideWeight")] public CFloat Neck_l_stretchAnimOverrideWeight { get; set; }
		[Ordinal(204)]  [RED("neck_r_stretchAnimOverrideWeight")] public CFloat Neck_r_stretchAnimOverrideWeight { get; set; }
		[Ordinal(205)]  [RED("neck_tightenAnimOverrideWeight")] public CFloat Neck_tightenAnimOverrideWeight { get; set; }
		[Ordinal(206)]  [RED("neck_l_sternocleidomastoid_flexAnimOverrideWeight")] public CFloat Neck_l_sternocleidomastoid_flexAnimOverrideWeight { get; set; }
		[Ordinal(207)]  [RED("neck_r_sternocleidomastoid_flexAnimOverrideWeight")] public CFloat Neck_r_sternocleidomastoid_flexAnimOverrideWeight { get; set; }
		[Ordinal(208)]  [RED("neck_l_platysma_flexAnimOverrideWeight")] public CFloat Neck_l_platysma_flexAnimOverrideWeight { get; set; }
		[Ordinal(209)]  [RED("neck_r_platysma_flexAnimOverrideWeight")] public CFloat Neck_r_platysma_flexAnimOverrideWeight { get; set; }
		[Ordinal(210)]  [RED("neck_throat_adamsApple_upAnimOverrideWeight")] public CFloat Neck_throat_adamsApple_upAnimOverrideWeight { get; set; }
		[Ordinal(211)]  [RED("neck_throat_adamsApple_dnAnimOverrideWeight")] public CFloat Neck_throat_adamsApple_dnAnimOverrideWeight { get; set; }
		[Ordinal(212)]  [RED("neck_throat_compressAnimOverrideWeight")] public CFloat Neck_throat_compressAnimOverrideWeight { get; set; }
		[Ordinal(213)]  [RED("neck_throat_openAnimOverrideWeight")] public CFloat Neck_throat_openAnimOverrideWeight { get; set; }
		[Ordinal(214)]  [RED("lips_corner_stickyAnimOverrideWeight")] public CFloat Lips_corner_stickyAnimOverrideWeight { get; set; }
		[Ordinal(215)]  [RED("lips_l_corner_up_in_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_l_corner_up_in_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(216)]  [RED("lips_l_corner_dn_in_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_l_corner_dn_in_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(217)]  [RED("lips_l_corner_up_out_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_l_corner_up_out_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(218)]  [RED("lips_l_corner_dn_out_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_l_corner_dn_out_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(219)]  [RED("lips_r_corner_up_in_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_r_corner_up_in_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(220)]  [RED("lips_r_corner_up_out_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_r_corner_up_out_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(221)]  [RED("lips_r_corner_dn_in_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_r_corner_dn_in_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(222)]  [RED("lips_r_corner_dn_out_sticky_cutSceneAnimOverrideWeight")] public CFloat Lips_r_corner_dn_out_sticky_cutSceneAnimOverrideWeight { get; set; }
		[Ordinal(223)]  [RED("tongue_mid_base_lAnimOverrideWeight")] public CFloat Tongue_mid_base_lAnimOverrideWeight { get; set; }
		[Ordinal(224)]  [RED("tongue_mid_base_rAnimOverrideWeight")] public CFloat Tongue_mid_base_rAnimOverrideWeight { get; set; }
		[Ordinal(225)]  [RED("tongue_mid_base_dnAnimOverrideWeight")] public CFloat Tongue_mid_base_dnAnimOverrideWeight { get; set; }
		[Ordinal(226)]  [RED("tongue_mid_base_upAnimOverrideWeight")] public CFloat Tongue_mid_base_upAnimOverrideWeight { get; set; }
		[Ordinal(227)]  [RED("tongue_mid_base_fwdAnimOverrideWeight")] public CFloat Tongue_mid_base_fwdAnimOverrideWeight { get; set; }
		[Ordinal(228)]  [RED("tongue_mid_base_frontAnimOverrideWeight")] public CFloat Tongue_mid_base_frontAnimOverrideWeight { get; set; }
		[Ordinal(229)]  [RED("tongue_mid_base_backAnimOverrideWeight")] public CFloat Tongue_mid_base_backAnimOverrideWeight { get; set; }
		[Ordinal(230)]  [RED("tongue_mid_fwdAnimOverrideWeight")] public CFloat Tongue_mid_fwdAnimOverrideWeight { get; set; }
		[Ordinal(231)]  [RED("tongue_mid_liftAnimOverrideWeight")] public CFloat Tongue_mid_liftAnimOverrideWeight { get; set; }
		[Ordinal(232)]  [RED("tongue_mid_tip_lAnimOverrideWeight")] public CFloat Tongue_mid_tip_lAnimOverrideWeight { get; set; }
		[Ordinal(233)]  [RED("tongue_mid_tip_rAnimOverrideWeight")] public CFloat Tongue_mid_tip_rAnimOverrideWeight { get; set; }
		[Ordinal(234)]  [RED("tongue_mid_tip_dnAnimOverrideWeight")] public CFloat Tongue_mid_tip_dnAnimOverrideWeight { get; set; }
		[Ordinal(235)]  [RED("tongue_mid_tip_upAnimOverrideWeight")] public CFloat Tongue_mid_tip_upAnimOverrideWeight { get; set; }
		[Ordinal(236)]  [RED("tongue_mid_twist_lAnimOverrideWeight")] public CFloat Tongue_mid_twist_lAnimOverrideWeight { get; set; }
		[Ordinal(237)]  [RED("tongue_mid_twist_rAnimOverrideWeight")] public CFloat Tongue_mid_twist_rAnimOverrideWeight { get; set; }
		[Ordinal(238)]  [RED("tongue_mid_thickAnimOverrideWeight")] public CFloat Tongue_mid_thickAnimOverrideWeight { get; set; }
		[Ordinal(239)]  [RED("eye_l_brows_raise_inLipsyncPoseOutput")] public CFloat Eye_l_brows_raise_inLipsyncPoseOutput { get; set; }
		[Ordinal(240)]  [RED("eye_r_brows_raise_inLipsyncPoseOutput")] public CFloat Eye_r_brows_raise_inLipsyncPoseOutput { get; set; }
		[Ordinal(241)]  [RED("eye_l_brows_raise_outLipsyncPoseOutput")] public CFloat Eye_l_brows_raise_outLipsyncPoseOutput { get; set; }
		[Ordinal(242)]  [RED("eye_r_brows_raise_outLipsyncPoseOutput")] public CFloat Eye_r_brows_raise_outLipsyncPoseOutput { get; set; }
		[Ordinal(243)]  [RED("eye_l_brows_lowerLipsyncPoseOutput")] public CFloat Eye_l_brows_lowerLipsyncPoseOutput { get; set; }
		[Ordinal(244)]  [RED("eye_r_brows_lowerLipsyncPoseOutput")] public CFloat Eye_r_brows_lowerLipsyncPoseOutput { get; set; }
		[Ordinal(245)]  [RED("eye_l_brows_lateralLipsyncPoseOutput")] public CFloat Eye_l_brows_lateralLipsyncPoseOutput { get; set; }
		[Ordinal(246)]  [RED("eye_r_brows_lateralLipsyncPoseOutput")] public CFloat Eye_r_brows_lateralLipsyncPoseOutput { get; set; }
		[Ordinal(247)]  [RED("eye_l_blinkLipsyncPoseOutput")] public CFloat Eye_l_blinkLipsyncPoseOutput { get; set; }
		[Ordinal(248)]  [RED("eye_r_blinkLipsyncPoseOutput")] public CFloat Eye_r_blinkLipsyncPoseOutput { get; set; }
		[Ordinal(249)]  [RED("eye_l_widenLipsyncPoseOutput")] public CFloat Eye_l_widenLipsyncPoseOutput { get; set; }
		[Ordinal(250)]  [RED("eye_r_widenLipsyncPoseOutput")] public CFloat Eye_r_widenLipsyncPoseOutput { get; set; }
		[Ordinal(251)]  [RED("eye_l_oculi_squint_innerLipsyncPoseOutput")] public CFloat Eye_l_oculi_squint_innerLipsyncPoseOutput { get; set; }
		[Ordinal(252)]  [RED("eye_r_oculi_squint_innerLipsyncPoseOutput")] public CFloat Eye_r_oculi_squint_innerLipsyncPoseOutput { get; set; }
		[Ordinal(253)]  [RED("eye_l_oculi_squint_outer_lowerLipsyncPoseOutput")] public CFloat Eye_l_oculi_squint_outer_lowerLipsyncPoseOutput { get; set; }
		[Ordinal(254)]  [RED("eye_r_oculi_squint_outer_lowerLipsyncPoseOutput")] public CFloat Eye_r_oculi_squint_outer_lowerLipsyncPoseOutput { get; set; }
		[Ordinal(255)]  [RED("eye_l_oculi_squint_outer_upperLipsyncPoseOutput")] public CFloat Eye_l_oculi_squint_outer_upperLipsyncPoseOutput { get; set; }
		[Ordinal(256)]  [RED("eye_r_oculi_squint_outer_upperLipsyncPoseOutput")] public CFloat Eye_r_oculi_squint_outer_upperLipsyncPoseOutput { get; set; }
		[Ordinal(257)]  [RED("nose_l_compressLipsyncPoseOutput")] public CFloat Nose_l_compressLipsyncPoseOutput { get; set; }
		[Ordinal(258)]  [RED("nose_r_compressLipsyncPoseOutput")] public CFloat Nose_r_compressLipsyncPoseOutput { get; set; }
		[Ordinal(259)]  [RED("nose_l_breathe_inLipsyncPoseOutput")] public CFloat Nose_l_breathe_inLipsyncPoseOutput { get; set; }
		[Ordinal(260)]  [RED("nose_r_breathe_inLipsyncPoseOutput")] public CFloat Nose_r_breathe_inLipsyncPoseOutput { get; set; }
		[Ordinal(261)]  [RED("nose_l_breathe_outLipsyncPoseOutput")] public CFloat Nose_l_breathe_outLipsyncPoseOutput { get; set; }
		[Ordinal(262)]  [RED("nose_r_breathe_outLipsyncPoseOutput")] public CFloat Nose_r_breathe_outLipsyncPoseOutput { get; set; }
		[Ordinal(263)]  [RED("nose_l_snearLipsyncPoseOutput")] public CFloat Nose_l_snearLipsyncPoseOutput { get; set; }
		[Ordinal(264)]  [RED("nose_r_snearLipsyncPoseOutput")] public CFloat Nose_r_snearLipsyncPoseOutput { get; set; }
		[Ordinal(265)]  [RED("lips_l_nasolabialDeepenerLipsyncPoseOutput")] public CFloat Lips_l_nasolabialDeepenerLipsyncPoseOutput { get; set; }
		[Ordinal(266)]  [RED("lips_r_nasolabialDeepenerLipsyncPoseOutput")] public CFloat Lips_r_nasolabialDeepenerLipsyncPoseOutput { get; set; }
		[Ordinal(267)]  [RED("lips_l_upper_raiseLipsyncPoseOutput")] public CFloat Lips_l_upper_raiseLipsyncPoseOutput { get; set; }
		[Ordinal(268)]  [RED("lips_r_upper_raiseLipsyncPoseOutput")] public CFloat Lips_r_upper_raiseLipsyncPoseOutput { get; set; }
		[Ordinal(269)]  [RED("lips_l_pullLipsyncPoseOutput")] public CFloat Lips_l_pullLipsyncPoseOutput { get; set; }
		[Ordinal(270)]  [RED("lips_r_pullLipsyncPoseOutput")] public CFloat Lips_r_pullLipsyncPoseOutput { get; set; }
		[Ordinal(271)]  [RED("lips_l_corner_upLipsyncPoseOutput")] public CFloat Lips_l_corner_upLipsyncPoseOutput { get; set; }
		[Ordinal(272)]  [RED("lips_r_corner_upLipsyncPoseOutput")] public CFloat Lips_r_corner_upLipsyncPoseOutput { get; set; }
		[Ordinal(273)]  [RED("lips_l_corner_wideLipsyncPoseOutput")] public CFloat Lips_l_corner_wideLipsyncPoseOutput { get; set; }
		[Ordinal(274)]  [RED("lips_r_corner_wideLipsyncPoseOutput")] public CFloat Lips_r_corner_wideLipsyncPoseOutput { get; set; }
		[Ordinal(275)]  [RED("lips_l_corner_stretchLipsyncPoseOutput")] public CFloat Lips_l_corner_stretchLipsyncPoseOutput { get; set; }
		[Ordinal(276)]  [RED("lips_r_corner_stretchLipsyncPoseOutput")] public CFloat Lips_r_corner_stretchLipsyncPoseOutput { get; set; }
		[Ordinal(277)]  [RED("lips_l_stretchLipsyncPoseOutput")] public CFloat Lips_l_stretchLipsyncPoseOutput { get; set; }
		[Ordinal(278)]  [RED("lips_r_stretchLipsyncPoseOutput")] public CFloat Lips_r_stretchLipsyncPoseOutput { get; set; }
		[Ordinal(279)]  [RED("lips_l_corner_sharp_upLipsyncPoseOutput")] public CFloat Lips_l_corner_sharp_upLipsyncPoseOutput { get; set; }
		[Ordinal(280)]  [RED("lips_r_corner_sharp_upLipsyncPoseOutput")] public CFloat Lips_r_corner_sharp_upLipsyncPoseOutput { get; set; }
		[Ordinal(281)]  [RED("lips_suck_upLipsyncPoseOutput")] public CFloat Lips_suck_upLipsyncPoseOutput { get; set; }
		[Ordinal(282)]  [RED("lips_suck_dnLipsyncPoseOutput")] public CFloat Lips_suck_dnLipsyncPoseOutput { get; set; }
		[Ordinal(283)]  [RED("lips_puff_upLipsyncPoseOutput")] public CFloat Lips_puff_upLipsyncPoseOutput { get; set; }
		[Ordinal(284)]  [RED("lips_puff_dnLipsyncPoseOutput")] public CFloat Lips_puff_dnLipsyncPoseOutput { get; set; }
		[Ordinal(285)]  [RED("lips_apart_upLipsyncPoseOutput")] public CFloat Lips_apart_upLipsyncPoseOutput { get; set; }
		[Ordinal(286)]  [RED("lips_apart_dnLipsyncPoseOutput")] public CFloat Lips_apart_dnLipsyncPoseOutput { get; set; }
		[Ordinal(287)]  [RED("lips_l_lower_raiseLipsyncPoseOutput")] public CFloat Lips_l_lower_raiseLipsyncPoseOutput { get; set; }
		[Ordinal(288)]  [RED("lips_r_lower_raiseLipsyncPoseOutput")] public CFloat Lips_r_lower_raiseLipsyncPoseOutput { get; set; }
		[Ordinal(289)]  [RED("lips_l_corner_dnLipsyncPoseOutput")] public CFloat Lips_l_corner_dnLipsyncPoseOutput { get; set; }
		[Ordinal(290)]  [RED("lips_r_corner_dnLipsyncPoseOutput")] public CFloat Lips_r_corner_dnLipsyncPoseOutput { get; set; }
		[Ordinal(291)]  [RED("lips_chin_raiseLipsyncPoseOutput")] public CFloat Lips_chin_raiseLipsyncPoseOutput { get; set; }
		[Ordinal(292)]  [RED("lips_together_upLipsyncPoseOutput")] public CFloat Lips_together_upLipsyncPoseOutput { get; set; }
		[Ordinal(293)]  [RED("lips_together_dnLipsyncPoseOutput")] public CFloat Lips_together_dnLipsyncPoseOutput { get; set; }
		[Ordinal(294)]  [RED("lips_l_purseLipsyncPoseOutput")] public CFloat Lips_l_purseLipsyncPoseOutput { get; set; }
		[Ordinal(295)]  [RED("lips_r_purseLipsyncPoseOutput")] public CFloat Lips_r_purseLipsyncPoseOutput { get; set; }
		[Ordinal(296)]  [RED("lips_l_funnelLipsyncPoseOutput")] public CFloat Lips_l_funnelLipsyncPoseOutput { get; set; }
		[Ordinal(297)]  [RED("lips_r_funnelLipsyncPoseOutput")] public CFloat Lips_r_funnelLipsyncPoseOutput { get; set; }
		[Ordinal(298)]  [RED("lips_tighten_upLipsyncPoseOutput")] public CFloat Lips_tighten_upLipsyncPoseOutput { get; set; }
		[Ordinal(299)]  [RED("lips_tighten_dnLipsyncPoseOutput")] public CFloat Lips_tighten_dnLipsyncPoseOutput { get; set; }
		[Ordinal(300)]  [RED("lips_mid_shift_lLipsyncPoseOutput")] public CFloat Lips_mid_shift_lLipsyncPoseOutput { get; set; }
		[Ordinal(301)]  [RED("lips_mid_shift_rLipsyncPoseOutput")] public CFloat Lips_mid_shift_rLipsyncPoseOutput { get; set; }
		[Ordinal(302)]  [RED("lips_mid_shift_upLipsyncPoseOutput")] public CFloat Lips_mid_shift_upLipsyncPoseOutput { get; set; }
		[Ordinal(303)]  [RED("lips_mid_shift_dnLipsyncPoseOutput")] public CFloat Lips_mid_shift_dnLipsyncPoseOutput { get; set; }
		[Ordinal(304)]  [RED("cheek_l_suckLipsyncPoseOutput")] public CFloat Cheek_l_suckLipsyncPoseOutput { get; set; }
		[Ordinal(305)]  [RED("cheek_r_suckLipsyncPoseOutput")] public CFloat Cheek_r_suckLipsyncPoseOutput { get; set; }
		[Ordinal(306)]  [RED("cheek_l_puffLipsyncPoseOutput")] public CFloat Cheek_l_puffLipsyncPoseOutput { get; set; }
		[Ordinal(307)]  [RED("cheek_r_puffLipsyncPoseOutput")] public CFloat Cheek_r_puffLipsyncPoseOutput { get; set; }
		[Ordinal(308)]  [RED("jaw_mid_openLipsyncPoseOutput")] public CFloat Jaw_mid_openLipsyncPoseOutput { get; set; }
		[Ordinal(309)]  [RED("jaw_mid_closeLipsyncPoseOutput")] public CFloat Jaw_mid_closeLipsyncPoseOutput { get; set; }
		[Ordinal(310)]  [RED("jaw_mid_shift_lLipsyncPoseOutput")] public CFloat Jaw_mid_shift_lLipsyncPoseOutput { get; set; }
		[Ordinal(311)]  [RED("jaw_mid_shift_rLipsyncPoseOutput")] public CFloat Jaw_mid_shift_rLipsyncPoseOutput { get; set; }
		[Ordinal(312)]  [RED("jaw_mid_shift_fwdLipsyncPoseOutput")] public CFloat Jaw_mid_shift_fwdLipsyncPoseOutput { get; set; }
		[Ordinal(313)]  [RED("jaw_mid_shift_backLipsyncPoseOutput")] public CFloat Jaw_mid_shift_backLipsyncPoseOutput { get; set; }
		[Ordinal(314)]  [RED("jaw_mid_clenchLipsyncPoseOutput")] public CFloat Jaw_mid_clenchLipsyncPoseOutput { get; set; }
		[Ordinal(315)]  [RED("neck_l_stretchLipsyncPoseOutput")] public CFloat Neck_l_stretchLipsyncPoseOutput { get; set; }
		[Ordinal(316)]  [RED("neck_r_stretchLipsyncPoseOutput")] public CFloat Neck_r_stretchLipsyncPoseOutput { get; set; }
		[Ordinal(317)]  [RED("neck_tightenLipsyncPoseOutput")] public CFloat Neck_tightenLipsyncPoseOutput { get; set; }
		[Ordinal(318)]  [RED("neck_l_sternocleidomastoid_flexLipsyncPoseOutput")] public CFloat Neck_l_sternocleidomastoid_flexLipsyncPoseOutput { get; set; }
		[Ordinal(319)]  [RED("neck_r_sternocleidomastoid_flexLipsyncPoseOutput")] public CFloat Neck_r_sternocleidomastoid_flexLipsyncPoseOutput { get; set; }
		[Ordinal(320)]  [RED("neck_l_platysma_flexLipsyncPoseOutput")] public CFloat Neck_l_platysma_flexLipsyncPoseOutput { get; set; }
		[Ordinal(321)]  [RED("neck_r_platysma_flexLipsyncPoseOutput")] public CFloat Neck_r_platysma_flexLipsyncPoseOutput { get; set; }
		[Ordinal(322)]  [RED("neck_throat_adamsApple_upLipsyncPoseOutput")] public CFloat Neck_throat_adamsApple_upLipsyncPoseOutput { get; set; }
		[Ordinal(323)]  [RED("neck_throat_adamsApple_dnLipsyncPoseOutput")] public CFloat Neck_throat_adamsApple_dnLipsyncPoseOutput { get; set; }
		[Ordinal(324)]  [RED("neck_throat_compressLipsyncPoseOutput")] public CFloat Neck_throat_compressLipsyncPoseOutput { get; set; }
		[Ordinal(325)]  [RED("neck_throat_openLipsyncPoseOutput")] public CFloat Neck_throat_openLipsyncPoseOutput { get; set; }
		[Ordinal(326)]  [RED("neck_l_turnLipsyncPoseOutput")] public CFloat Neck_l_turnLipsyncPoseOutput { get; set; }
		[Ordinal(327)]  [RED("neck_r_turnLipsyncPoseOutput")] public CFloat Neck_r_turnLipsyncPoseOutput { get; set; }
		[Ordinal(328)]  [RED("neck_up_turnLipsyncPoseOutput")] public CFloat Neck_up_turnLipsyncPoseOutput { get; set; }
		[Ordinal(329)]  [RED("neck_dn_turnLipsyncPoseOutput")] public CFloat Neck_dn_turnLipsyncPoseOutput { get; set; }
		[Ordinal(330)]  [RED("neck_l_tiltLipsyncPoseOutput")] public CFloat Neck_l_tiltLipsyncPoseOutput { get; set; }
		[Ordinal(331)]  [RED("neck_r_tiltLipsyncPoseOutput")] public CFloat Neck_r_tiltLipsyncPoseOutput { get; set; }
		[Ordinal(332)]  [RED("head_neck_up_turnLipsyncPoseOutput")] public CFloat Head_neck_up_turnLipsyncPoseOutput { get; set; }
		[Ordinal(333)]  [RED("head_neck_dn_turnLipsyncPoseOutput")] public CFloat Head_neck_dn_turnLipsyncPoseOutput { get; set; }
		[Ordinal(334)]  [RED("head_neck_l_tiltLipsyncPoseOutput")] public CFloat Head_neck_l_tiltLipsyncPoseOutput { get; set; }
		[Ordinal(335)]  [RED("head_neck_r_tiltLipsyncPoseOutput")] public CFloat Head_neck_r_tiltLipsyncPoseOutput { get; set; }
		[Ordinal(336)]  [RED("ear_l_shift_upLipsyncPoseOutput")] public CFloat Ear_l_shift_upLipsyncPoseOutput { get; set; }
		[Ordinal(337)]  [RED("ear_r_shift_upLipsyncPoseOutput")] public CFloat Ear_r_shift_upLipsyncPoseOutput { get; set; }
		[Ordinal(338)]  [RED("sculp_mid_slideLipsyncPoseOutput")] public CFloat Sculp_mid_slideLipsyncPoseOutput { get; set; }
		[Ordinal(339)]  [RED("eye_l_dir_upLipsyncPoseOutput")] public CFloat Eye_l_dir_upLipsyncPoseOutput { get; set; }
		[Ordinal(340)]  [RED("eye_l_dir_dnLipsyncPoseOutput")] public CFloat Eye_l_dir_dnLipsyncPoseOutput { get; set; }
		[Ordinal(341)]  [RED("eye_l_dir_inLipsyncPoseOutput")] public CFloat Eye_l_dir_inLipsyncPoseOutput { get; set; }
		[Ordinal(342)]  [RED("eye_l_dir_outLipsyncPoseOutput")] public CFloat Eye_l_dir_outLipsyncPoseOutput { get; set; }
		[Ordinal(343)]  [RED("eye_r_dir_upLipsyncPoseOutput")] public CFloat Eye_r_dir_upLipsyncPoseOutput { get; set; }
		[Ordinal(344)]  [RED("eye_r_dir_dnLipsyncPoseOutput")] public CFloat Eye_r_dir_dnLipsyncPoseOutput { get; set; }
		[Ordinal(345)]  [RED("eye_r_dir_inLipsyncPoseOutput")] public CFloat Eye_r_dir_inLipsyncPoseOutput { get; set; }
		[Ordinal(346)]  [RED("eye_r_dir_outLipsyncPoseOutput")] public CFloat Eye_r_dir_outLipsyncPoseOutput { get; set; }
		[Ordinal(347)]  [RED("face_gravity_fwdLipsyncPoseOutput")] public CFloat Face_gravity_fwdLipsyncPoseOutput { get; set; }
		[Ordinal(348)]  [RED("face_gravity_backLipsyncPoseOutput")] public CFloat Face_gravity_backLipsyncPoseOutput { get; set; }
		[Ordinal(349)]  [RED("face_gravity_lLipsyncPoseOutput")] public CFloat Face_gravity_lLipsyncPoseOutput { get; set; }
		[Ordinal(350)]  [RED("face_gravity_rLipsyncPoseOutput")] public CFloat Face_gravity_rLipsyncPoseOutput { get; set; }
		[Ordinal(351)]  [RED("lips_corner_stickyLipsyncPoseOutput")] public CFloat Lips_corner_stickyLipsyncPoseOutput { get; set; }
		[Ordinal(352)]  [RED("lips_l_corner_up_in_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_l_corner_up_in_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(353)]  [RED("lips_l_corner_dn_in_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_l_corner_dn_in_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(354)]  [RED("lips_l_corner_up_out_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_l_corner_up_out_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(355)]  [RED("lips_l_corner_dn_out_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_l_corner_dn_out_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(356)]  [RED("lips_r_corner_up_in_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_r_corner_up_in_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(357)]  [RED("lips_r_corner_up_out_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_r_corner_up_out_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(358)]  [RED("lips_r_corner_dn_in_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_r_corner_dn_in_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(359)]  [RED("lips_r_corner_dn_out_sticky_cutSceneLipsyncPoseOutput")] public CFloat Lips_r_corner_dn_out_sticky_cutSceneLipsyncPoseOutput { get; set; }
		[Ordinal(360)]  [RED("eye_l_pupil_narrowLipsyncPoseOutput")] public CFloat Eye_l_pupil_narrowLipsyncPoseOutput { get; set; }
		[Ordinal(361)]  [RED("eye_r_pupil_narrowLipsyncPoseOutput")] public CFloat Eye_r_pupil_narrowLipsyncPoseOutput { get; set; }
		[Ordinal(362)]  [RED("eye_l_pupil_wideLipsyncPoseOutput")] public CFloat Eye_l_pupil_wideLipsyncPoseOutput { get; set; }
		[Ordinal(363)]  [RED("eye_r_pupil_wideLipsyncPoseOutput")] public CFloat Eye_r_pupil_wideLipsyncPoseOutput { get; set; }
		[Ordinal(364)]  [RED("tongue_mid_base_lLipsyncPoseOutput")] public CFloat Tongue_mid_base_lLipsyncPoseOutput { get; set; }
		[Ordinal(365)]  [RED("tongue_mid_base_rLipsyncPoseOutput")] public CFloat Tongue_mid_base_rLipsyncPoseOutput { get; set; }
		[Ordinal(366)]  [RED("tongue_mid_base_dnLipsyncPoseOutput")] public CFloat Tongue_mid_base_dnLipsyncPoseOutput { get; set; }
		[Ordinal(367)]  [RED("tongue_mid_base_upLipsyncPoseOutput")] public CFloat Tongue_mid_base_upLipsyncPoseOutput { get; set; }
		[Ordinal(368)]  [RED("tongue_mid_base_fwdLipsyncPoseOutput")] public CFloat Tongue_mid_base_fwdLipsyncPoseOutput { get; set; }
		[Ordinal(369)]  [RED("tongue_mid_base_frontLipsyncPoseOutput")] public CFloat Tongue_mid_base_frontLipsyncPoseOutput { get; set; }
		[Ordinal(370)]  [RED("tongue_mid_base_backLipsyncPoseOutput")] public CFloat Tongue_mid_base_backLipsyncPoseOutput { get; set; }
		[Ordinal(371)]  [RED("tongue_mid_fwdLipsyncPoseOutput")] public CFloat Tongue_mid_fwdLipsyncPoseOutput { get; set; }
		[Ordinal(372)]  [RED("tongue_mid_liftLipsyncPoseOutput")] public CFloat Tongue_mid_liftLipsyncPoseOutput { get; set; }
		[Ordinal(373)]  [RED("tongue_mid_tip_lLipsyncPoseOutput")] public CFloat Tongue_mid_tip_lLipsyncPoseOutput { get; set; }
		[Ordinal(374)]  [RED("tongue_mid_tip_rLipsyncPoseOutput")] public CFloat Tongue_mid_tip_rLipsyncPoseOutput { get; set; }
		[Ordinal(375)]  [RED("tongue_mid_tip_dnLipsyncPoseOutput")] public CFloat Tongue_mid_tip_dnLipsyncPoseOutput { get; set; }
		[Ordinal(376)]  [RED("tongue_mid_tip_upLipsyncPoseOutput")] public CFloat Tongue_mid_tip_upLipsyncPoseOutput { get; set; }
		[Ordinal(377)]  [RED("tongue_mid_twist_lLipsyncPoseOutput")] public CFloat Tongue_mid_twist_lLipsyncPoseOutput { get; set; }
		[Ordinal(378)]  [RED("tongue_mid_twist_rLipsyncPoseOutput")] public CFloat Tongue_mid_twist_rLipsyncPoseOutput { get; set; }
		[Ordinal(379)]  [RED("tongue_mid_thickLipsyncPoseOutput")] public CFloat Tongue_mid_thickLipsyncPoseOutput { get; set; }
		[Ordinal(380)]  [RED("eye_l_brows_raise_inWrnkl")] public CFloat Eye_l_brows_raise_inWrnkl { get; set; }
		[Ordinal(381)]  [RED("eye_r_brows_raise_inWrnkl")] public CFloat Eye_r_brows_raise_inWrnkl { get; set; }
		[Ordinal(382)]  [RED("eye_l_brows_raise_outWrnkl")] public CFloat Eye_l_brows_raise_outWrnkl { get; set; }
		[Ordinal(383)]  [RED("eye_r_brows_raise_outWrnkl")] public CFloat Eye_r_brows_raise_outWrnkl { get; set; }
		[Ordinal(384)]  [RED("eye_l_brows_lowerWrnkl")] public CFloat Eye_l_brows_lowerWrnkl { get; set; }
		[Ordinal(385)]  [RED("eye_r_brows_lowerWrnkl")] public CFloat Eye_r_brows_lowerWrnkl { get; set; }
		[Ordinal(386)]  [RED("eye_l_brows_lateralWrnkl")] public CFloat Eye_l_brows_lateralWrnkl { get; set; }
		[Ordinal(387)]  [RED("eye_r_brows_lateralWrnkl")] public CFloat Eye_r_brows_lateralWrnkl { get; set; }
		[Ordinal(388)]  [RED("eye_l_oculi_squint_outer_lowerWrnkl")] public CFloat Eye_l_oculi_squint_outer_lowerWrnkl { get; set; }
		[Ordinal(389)]  [RED("eye_r_oculi_squint_outer_lowerWrnkl")] public CFloat Eye_r_oculi_squint_outer_lowerWrnkl { get; set; }
		[Ordinal(390)]  [RED("eye_l_oculi_squint_outer_upperWrnkl")] public CFloat Eye_l_oculi_squint_outer_upperWrnkl { get; set; }
		[Ordinal(391)]  [RED("eye_r_oculi_squint_outer_upperWrnkl")] public CFloat Eye_r_oculi_squint_outer_upperWrnkl { get; set; }
		[Ordinal(392)]  [RED("nose_l_snearWrnkl")] public CFloat Nose_l_snearWrnkl { get; set; }
		[Ordinal(393)]  [RED("nose_r_snearWrnkl")] public CFloat Nose_r_snearWrnkl { get; set; }
		[Ordinal(394)]  [RED("lips_l_upper_raiseWrnkl")] public CFloat Lips_l_upper_raiseWrnkl { get; set; }
		[Ordinal(395)]  [RED("lips_r_upper_raiseWrnkl")] public CFloat Lips_r_upper_raiseWrnkl { get; set; }
		[Ordinal(396)]  [RED("lips_l_corner_upWrnkl")] public CFloat Lips_l_corner_upWrnkl { get; set; }
		[Ordinal(397)]  [RED("lips_r_corner_upWrnkl")] public CFloat Lips_r_corner_upWrnkl { get; set; }
		[Ordinal(398)]  [RED("lips_l_corner_wideWrnkl")] public CFloat Lips_l_corner_wideWrnkl { get; set; }
		[Ordinal(399)]  [RED("lips_r_corner_wideWrnkl")] public CFloat Lips_r_corner_wideWrnkl { get; set; }
		[Ordinal(400)]  [RED("lips_l_corner_stretchWrnkl")] public CFloat Lips_l_corner_stretchWrnkl { get; set; }
		[Ordinal(401)]  [RED("lips_r_corner_stretchWrnkl")] public CFloat Lips_r_corner_stretchWrnkl { get; set; }
		[Ordinal(402)]  [RED("lips_l_lower_raiseWrnkl")] public CFloat Lips_l_lower_raiseWrnkl { get; set; }
		[Ordinal(403)]  [RED("lips_r_lower_raiseWrnkl")] public CFloat Lips_r_lower_raiseWrnkl { get; set; }
		[Ordinal(404)]  [RED("lips_chin_raiseWrnkl")] public CFloat Lips_chin_raiseWrnkl { get; set; }
		[Ordinal(405)]  [RED("lips_l_purseWrnkl")] public CFloat Lips_l_purseWrnkl { get; set; }
		[Ordinal(406)]  [RED("lips_r_purseWrnkl")] public CFloat Lips_r_purseWrnkl { get; set; }
		[Ordinal(407)]  [RED("lips_l_funnelWrnkl")] public CFloat Lips_l_funnelWrnkl { get; set; }
		[Ordinal(408)]  [RED("lips_r_funnelWrnkl")] public CFloat Lips_r_funnelWrnkl { get; set; }
		[Ordinal(409)]  [RED("jaw_mid_openWrnkl")] public CFloat Jaw_mid_openWrnkl { get; set; }
		[Ordinal(410)]  [RED("neck_l_stretchWrnkl")] public CFloat Neck_l_stretchWrnkl { get; set; }
		[Ordinal(411)]  [RED("neck_r_stretchWrnkl")] public CFloat Neck_r_stretchWrnkl { get; set; }
		[Ordinal(412)]  [RED("head_neck_dn_turnWrnkl")] public CFloat Head_neck_dn_turnWrnkl { get; set; }

		public animSermoTestController(CR2WFile cr2w, CVariable parent, string name) : base(cr2w, parent, name) { }
	}
}
