using System.IO;
using CP77.CR2W.Reflection;
using FastMember;
using static CP77.CR2W.Types.Enums;

namespace CP77.CR2W.Types
{
	[REDMeta]
	public class PlayerPuppet : ScriptedPuppet
	{
		[Ordinal(0)]  [RED("e3HighlightHackStarted")] public CBool E3HighlightHackStarted { get; set; }
		[Ordinal(1)]  [RED("e3ObjectRevealed")] public CBool E3ObjectRevealed { get; set; }
		[Ordinal(2)]  [RED("DEBUG_Visualizer")] public CHandle<DEBUG_VisualizerComponent> DEBUG_Visualizer { get; set; }
		[Ordinal(3)]  [RED("Debug_DamageInputRec")] public CHandle<DEBUG_DamageInputReceiver> Debug_DamageInputRec { get; set; }
		[Ordinal(4)]  [RED("CPOMissionDataState")] public CHandle<CPOMissionDataState> CPOMissionDataState { get; set; }
		[Ordinal(5)]  [RED("CPOMissionDataBbId")] public CUInt32 CPOMissionDataBbId { get; set; }
		[Ordinal(6)]  [RED("securityAreaTypeE3HACK")] public CEnum<ESecurityAreaType> SecurityAreaTypeE3HACK { get; set; }
		[Ordinal(7)]  [RED("forceRegisterInHudManager")] public CBool ForceRegisterInHudManager { get; set; }
		[Ordinal(8)]  [RED("prereqListeners")] public CArray<CHandle<GameObjectListener>> PrereqListeners { get; set; }
		[Ordinal(9)]  [RED("statusEffectListeners")] public CArray<CHandle<StatusEffectTriggerListener>> StatusEffectListeners { get; set; }
		[Ordinal(10)]  [RED("outlineRequestsManager")] public CHandle<OutlineRequestManager> OutlineRequestsManager { get; set; }
		[Ordinal(11)]  [RED("outlineFadeCounter")] public CInt32 OutlineFadeCounter { get; set; }
		[Ordinal(12)]  [RED("fadeOutStarted")] public CBool FadeOutStarted { get; set; }
		[Ordinal(13)]  [RED("lastEngineTime")] public CFloat LastEngineTime { get; set; }
		[Ordinal(14)]  [RED("accumulatedTimePasssed")] public CFloat AccumulatedTimePasssed { get; set; }
		[Ordinal(15)]  [RED("scanningComponent")] public CHandle<gameScanningComponent> ScanningComponent { get; set; }
		[Ordinal(16)]  [RED("visionComponent")] public CHandle<gameVisionModeComponent> VisionComponent { get; set; }
		[Ordinal(17)]  [RED("isHighlightedInFocusMode")] public CBool IsHighlightedInFocusMode { get; set; }
		[Ordinal(18)]  [RED("statusEffectComponent")] public CHandle<gameStatusEffectComponent> StatusEffectComponent { get; set; }
		[Ordinal(19)]  [RED("lastFrameGreen")] public CHandle<OutlineRequest> LastFrameGreen { get; set; }
		[Ordinal(20)]  [RED("lastFrameRed")] public CHandle<OutlineRequest> LastFrameRed { get; set; }
		[Ordinal(21)]  [RED("markAsQuest")] public CBool MarkAsQuest { get; set; }
		[Ordinal(22)]  [RED("forceHighlightSource")] public entEntityID ForceHighlightSource { get; set; }
		[Ordinal(23)]  [RED("workspotMapper")] public CHandle<WorkspotMapperComponent> WorkspotMapper { get; set; }
		[Ordinal(24)]  [RED("stimBroadcaster")] public CHandle<StimBroadcasterComponent> StimBroadcaster { get; set; }
		[Ordinal(25)]  [RED("uiSlotComponent")] public CHandle<entSlotComponent> UiSlotComponent { get; set; }
		[Ordinal(26)]  [RED("squadMemberComponent")] public CHandle<SquadMemberBaseComponent> SquadMemberComponent { get; set; }
		[Ordinal(27)]  [RED("sourceShootComponent")] public CHandle<gameSourceShootComponent> SourceShootComponent { get; set; }
		[Ordinal(28)]  [RED("targetShootComponent")] public CHandle<gameTargetShootComponent> TargetShootComponent { get; set; }
		[Ordinal(29)]  [RED("receivedDamageHistory")] public CArray<DamageHistoryEntry> ReceivedDamageHistory { get; set; }
		[Ordinal(30)]  [RED("forceDefeatReward")] public CBool ForceDefeatReward { get; set; }
		[Ordinal(31)]  [RED("killRewardDisabled")] public CBool KillRewardDisabled { get; set; }
		[Ordinal(32)]  [RED("willDieSoon")] public CBool WillDieSoon { get; set; }
		[Ordinal(33)]  [RED("isScannerDataDirty")] public CBool IsScannerDataDirty { get; set; }
		[Ordinal(34)]  [RED("hasVisibilityForcedInAnimSystem")] public CBool HasVisibilityForcedInAnimSystem { get; set; }
		[Ordinal(35)]  [RED("isDead")] public CBool IsDead { get; set; }
		[Ordinal(36)]  [RED("aiController")] public CHandle<AIHumanComponent> AiController { get; set; }
		[Ordinal(37)]  [RED("movePolicies")] public CHandle<movePoliciesComponent> MovePolicies { get; set; }
		[Ordinal(38)]  [RED("aiStateHandlerComponent")] public CHandle<AIPhaseStateEventHandlerComponent> AiStateHandlerComponent { get; set; }
		[Ordinal(39)]  [RED("hitReactionComponent")] public CHandle<HitReactionComponent> HitReactionComponent { get; set; }
		[Ordinal(40)]  [RED("signalHandlerComponent")] public CHandle<AISignalHandlerComponent> SignalHandlerComponent { get; set; }
		[Ordinal(41)]  [RED("reactionComponent")] public CHandle<ReactionManagerComponent> ReactionComponent { get; set; }
		[Ordinal(42)]  [RED("dismembermentComponent")] public CHandle<gameDismembermentComponent> DismembermentComponent { get; set; }
		[Ordinal(43)]  [RED("hitRepresantation")] public CHandle<entSlotComponent> HitRepresantation { get; set; }
		[Ordinal(44)]  [RED("interactionComponent")] public CHandle<gameinteractionsComponent> InteractionComponent { get; set; }
		[Ordinal(45)]  [RED("slotComponent")] public CHandle<entSlotComponent> SlotComponent { get; set; }
		[Ordinal(46)]  [RED("sensesComponent")] public CHandle<senseComponent> SensesComponent { get; set; }
		[Ordinal(47)]  [RED("visibleObjectComponent")] public CHandle<senseVisibleObjectComponent> VisibleObjectComponent { get; set; }
		[Ordinal(48)]  [RED("sensorObjectComponent")] public CHandle<senseSensorObjectComponent> SensorObjectComponent { get; set; }
		[Ordinal(49)]  [RED("targetTrackerComponent")] public CHandle<AITargetTrackerComponent> TargetTrackerComponent { get; set; }
		[Ordinal(50)]  [RED("targetingComponentsArray")] public CArray<CHandle<gameTargetingComponent>> TargetingComponentsArray { get; set; }
		[Ordinal(51)]  [RED("statesComponent")] public CHandle<NPCStatesComponent> StatesComponent { get; set; }
		[Ordinal(52)]  [RED("fxResourceMapper")] public CHandle<FxResourceMapperComponent> FxResourceMapper { get; set; }
		[Ordinal(53)]  [RED("linkedStatusEffect")] public LinkedStatusEffect LinkedStatusEffect { get; set; }
		[Ordinal(54)]  [RED("resourceLibraryComponent")] public CHandle<ResourceLibraryComponent> ResourceLibraryComponent { get; set; }
		[Ordinal(55)]  [RED("crowdMemberComponent")] public CHandle<CrowdMemberBaseComponent> CrowdMemberComponent { get; set; }
		[Ordinal(56)]  [RED("inventoryComponent")] public CHandle<gameInventory> InventoryComponent { get; set; }
		[Ordinal(57)]  [RED("objectSelectionComponent")] public CHandle<AIObjectSelectionComponent> ObjectSelectionComponent { get; set; }
		[Ordinal(58)]  [RED("transformHistoryComponent")] public CHandle<entTransformHistoryComponent> TransformHistoryComponent { get; set; }
		[Ordinal(59)]  [RED("animationControllerComponent")] public CHandle<entAnimationControllerComponent> AnimationControllerComponent { get; set; }
		[Ordinal(60)]  [RED("bumpComponent")] public CHandle<gameinfluenceBumpComponent> BumpComponent { get; set; }
		[Ordinal(61)]  [RED("isCrowd")] public CBool IsCrowd { get; set; }
		[Ordinal(62)]  [RED("isIconic")] public CBool IsIconic { get; set; }
		[Ordinal(63)]  [RED("combatHUDManager")] public CHandle<CombatHUDManager> CombatHUDManager { get; set; }
		[Ordinal(64)]  [RED("exposePosition")] public CBool ExposePosition { get; set; }
		[Ordinal(65)]  [RED("puppetStateBlackboard")] public CHandle<gameIBlackboard> PuppetStateBlackboard { get; set; }
		[Ordinal(66)]  [RED("customBlackboard")] public CHandle<gameIBlackboard> CustomBlackboard { get; set; }
		[Ordinal(67)]  [RED("securityAreaCallbackID")] public CUInt32 SecurityAreaCallbackID { get; set; }
		[Ordinal(68)]  [RED("customAIComponents")] public CArray<CHandle<AICustomComponents>> CustomAIComponents { get; set; }
		[Ordinal(69)]  [RED("listeners")] public CArray<CHandle<PuppetListener>> Listeners { get; set; }
		[Ordinal(70)]  [RED("securitySupportListener")] public CHandle<SecuritySupportListener> SecuritySupportListener { get; set; }
		[Ordinal(71)]  [RED("shouldBeRevealedStorage")] public CHandle<RevealRequestsStorage> ShouldBeRevealedStorage { get; set; }
		[Ordinal(72)]  [RED("inputProcessed")] public CBool InputProcessed { get; set; }
		[Ordinal(73)]  [RED("targetedBlackBoard")] public CHandle<gameIBlackboard> TargetedBlackBoard { get; set; }
		[Ordinal(74)]  [RED("shouldSpawnBloodPuddle")] public CBool ShouldSpawnBloodPuddle { get; set; }
		[Ordinal(75)]  [RED("bloodPuddleSpawned")] public CBool BloodPuddleSpawned { get; set; }
		[Ordinal(76)]  [RED("skipDeathAnimation")] public CBool SkipDeathAnimation { get; set; }
		[Ordinal(77)]  [RED("hitHistory")] public CHandle<HitHistory> HitHistory { get; set; }
		[Ordinal(78)]  [RED("currentWorkspotTags")] public CArray<CName> CurrentWorkspotTags { get; set; }
		[Ordinal(79)]  [RED("lootQuality")] public CEnum<gamedataQuality> LootQuality { get; set; }
		[Ordinal(80)]  [RED("hasQuestItems")] public CBool HasQuestItems { get; set; }
		[Ordinal(81)]  [RED("activeQualityRangeInteraction")] public CName ActiveQualityRangeInteraction { get; set; }
		[Ordinal(82)]  [RED("weakspotComponent")] public CHandle<gameWeakspotComponent> WeakspotComponent { get; set; }
		[Ordinal(83)]  [RED("highlightData")] public CHandle<FocusForcedHighlightData> HighlightData { get; set; }
		[Ordinal(84)]  [RED("killer")] public wCHandle<entEntity> Killer { get; set; }
		[Ordinal(85)]  [RED("objectActionsCallbackCtrl")] public CHandle<gameObjectActionsCallbackController> ObjectActionsCallbackCtrl { get; set; }
		[Ordinal(86)]  [RED("isActiveCached")] public AIUtilsCachedBoolValue IsActiveCached { get; set; }
		[Ordinal(87)]  [RED("isCyberpsycho")] public CBool IsCyberpsycho { get; set; }
		[Ordinal(88)]  [RED("isCivilian")] public CBool IsCivilian { get; set; }
		[Ordinal(89)]  [RED("isPolice")] public CBool IsPolice { get; set; }
		[Ordinal(90)]  [RED("isGanger")] public CBool IsGanger { get; set; }
		[Ordinal(91)]  [RED("attemptedShards")] public CArray<ItemID> AttemptedShards { get; set; }
		[Ordinal(92)]  [RED("quickSlotsManager")] public CHandle<QuickSlotsManager> QuickSlotsManager { get; set; }
		[Ordinal(93)]  [RED("inspectionComponent")] public CHandle<InspectionComponent> InspectionComponent { get; set; }
		[Ordinal(94)]  [RED("Phone")] public CHandle<PlayerPhone> Phone { get; set; }
		[Ordinal(95)]  [RED("fppCameraComponent")] public CHandle<gameFPPCameraComponent> FppCameraComponent { get; set; }
		[Ordinal(96)]  [RED("primaryTargetingComponent")] public CHandle<gameTargetingComponent> PrimaryTargetingComponent { get; set; }
		[Ordinal(97)]  [RED("highDamageThreshold")] public CFloat HighDamageThreshold { get; set; }
		[Ordinal(98)]  [RED("medDamageThreshold")] public CFloat MedDamageThreshold { get; set; }
		[Ordinal(99)]  [RED("lowDamageThreshold")] public CFloat LowDamageThreshold { get; set; }
		[Ordinal(100)]  [RED("meleeHighDamageThreshold")] public CFloat MeleeHighDamageThreshold { get; set; }
		[Ordinal(101)]  [RED("meleeMedDamageThreshold")] public CFloat MeleeMedDamageThreshold { get; set; }
		[Ordinal(102)]  [RED("meleeLowDamageThreshold")] public CFloat MeleeLowDamageThreshold { get; set; }
		[Ordinal(103)]  [RED("explosionHighDamageThreshold")] public CFloat ExplosionHighDamageThreshold { get; set; }
		[Ordinal(104)]  [RED("explosionMedDamageThreshold")] public CFloat ExplosionMedDamageThreshold { get; set; }
		[Ordinal(105)]  [RED("explosionLowDamageThreshold")] public CFloat ExplosionLowDamageThreshold { get; set; }
		[Ordinal(106)]  [RED("effectTimeStamp")] public CFloat EffectTimeStamp { get; set; }
		[Ordinal(107)]  [RED("curInventoryWeight")] public CFloat CurInventoryWeight { get; set; }
		[Ordinal(108)]  [RED("healthVfxBlackboard")] public CHandle<worldEffectBlackboard> HealthVfxBlackboard { get; set; }
		[Ordinal(109)]  [RED("laserTargettingVfxBlackboard")] public CHandle<worldEffectBlackboard> LaserTargettingVfxBlackboard { get; set; }
		[Ordinal(110)]  [RED("itemLogBlackboard")] public CHandle<gameIBlackboard> ItemLogBlackboard { get; set; }
		[Ordinal(111)]  [RED("lastScanTarget")] public wCHandle<gameObject> LastScanTarget { get; set; }
		[Ordinal(112)]  [RED("meleeSelectInputProcessed")] public CBool MeleeSelectInputProcessed { get; set; }
		[Ordinal(113)]  [RED("waitingForDelayEvent")] public CBool WaitingForDelayEvent { get; set; }
		[Ordinal(114)]  [RED("randomizedTime")] public CFloat RandomizedTime { get; set; }
		[Ordinal(115)]  [RED("isResetting")] public CBool IsResetting { get; set; }
		[Ordinal(116)]  [RED("delayEventID")] public gameDelayID DelayEventID { get; set; }
		[Ordinal(117)]  [RED("resetTickID")] public gameDelayID ResetTickID { get; set; }
		[Ordinal(118)]  [RED("katanaAnimProgression")] public CFloat KatanaAnimProgression { get; set; }
		[Ordinal(119)]  [RED("coverModifierActive")] public CBool CoverModifierActive { get; set; }
		[Ordinal(120)]  [RED("workspotDamageReductionActive")] public CBool WorkspotDamageReductionActive { get; set; }
		[Ordinal(121)]  [RED("workspotVisibilityReductionActive")] public CBool WorkspotVisibilityReductionActive { get; set; }
		[Ordinal(122)]  [RED("currentPlayerWorkspotTags")] public CArray<CName> CurrentPlayerWorkspotTags { get; set; }
		[Ordinal(123)]  [RED("incapacitated")] public CBool Incapacitated { get; set; }
		[Ordinal(124)]  [RED("remoteMappinId")] public gameNewMappinID RemoteMappinId { get; set; }
		[Ordinal(125)]  [RED("armorStatListener")] public CHandle<ArmorStatListener> ArmorStatListener { get; set; }
		[Ordinal(126)]  [RED("healthStatListener")] public CHandle<HealthStatListener> HealthStatListener { get; set; }
		[Ordinal(127)]  [RED("oxygenStatListener")] public CHandle<OxygenStatListener> OxygenStatListener { get; set; }
		[Ordinal(128)]  [RED("aimAssistListener")] public CHandle<AimAssistSettingsListener> AimAssistListener { get; set; }
		[Ordinal(129)]  [RED("autoRevealListener")] public CHandle<AutoRevealStatListener> AutoRevealListener { get; set; }
		[Ordinal(130)]  [RED("isTalkingOnPhone")] public CBool IsTalkingOnPhone { get; set; }
		[Ordinal(131)]  [RED("DataDamageUpdateID")] public gameDelayID DataDamageUpdateID { get; set; }
		[Ordinal(132)]  [RED("playerAttachedCallbackID")] public CUInt32 PlayerAttachedCallbackID { get; set; }
		[Ordinal(133)]  [RED("playerDetachedCallbackID")] public CUInt32 PlayerDetachedCallbackID { get; set; }
		[Ordinal(134)]  [RED("combatStateListener")] public CUInt32 CombatStateListener { get; set; }
		[Ordinal(135)]  [RED("LocomotionStateListener")] public CUInt32 LocomotionStateListener { get; set; }
		[Ordinal(136)]  [RED("numberOfCombatantsListenerID")] public CUInt32 NumberOfCombatantsListenerID { get; set; }
		[Ordinal(137)]  [RED("numberOfCombatants")] public CInt32 NumberOfCombatants { get; set; }
		[Ordinal(138)]  [RED("zoneChangeListener")] public CUInt32 ZoneChangeListener { get; set; }
		[Ordinal(139)]  [RED("coverVisibilityPerkBlocked")] public CBool CoverVisibilityPerkBlocked { get; set; }
		[Ordinal(140)]  [RED("behindCover")] public CBool BehindCover { get; set; }
		[Ordinal(141)]  [RED("inCombat")] public CBool InCombat { get; set; }
		[Ordinal(142)]  [RED("hasBeenDetected")] public CBool HasBeenDetected { get; set; }
		[Ordinal(143)]  [RED("inCrouch")] public CBool InCrouch { get; set; }
		[Ordinal(144)]  [RED("gunshotRange")] public CFloat GunshotRange { get; set; }
		[Ordinal(145)]  [RED("explosionRange")] public CFloat ExplosionRange { get; set; }
		[Ordinal(146)]  [RED("nextBufferModifier")] public CInt32 NextBufferModifier { get; set; }
		[Ordinal(147)]  [RED("attackingNetrunnerID")] public entEntityID AttackingNetrunnerID { get; set; }
		[Ordinal(148)]  [RED("NPCDeathInstigator")] public wCHandle<NPCPuppet> NPCDeathInstigator { get; set; }
		[Ordinal(149)]  [RED("bestTargettingWeapon")] public wCHandle<gameweaponObject> BestTargettingWeapon { get; set; }
		[Ordinal(150)]  [RED("bestTargettingDot")] public CFloat BestTargettingDot { get; set; }
		[Ordinal(151)]  [RED("targettingEnemies")] public CInt32 TargettingEnemies { get; set; }
		[Ordinal(152)]  [RED("coverRecordID")] public TweakDBID CoverRecordID { get; set; }
		[Ordinal(153)]  [RED("damageReductionRecordID")] public TweakDBID DamageReductionRecordID { get; set; }
		[Ordinal(154)]  [RED("visReductionRecordID")] public TweakDBID VisReductionRecordID { get; set; }
		[Ordinal(155)]  [RED("lastDmgInflicted")] public EngineTime LastDmgInflicted { get; set; }
		[Ordinal(156)]  [RED("lowHealthNextRumbleTime")] public CFloat LowHealthNextRumbleTime { get; set; }
		[Ordinal(157)]  [RED("overlappedSecurityZones")] public CArray<gamePersistentID> OverlappedSecurityZones { get; set; }
		[Ordinal(158)]  [RED("interestingFacts")] public InterestingFacts InterestingFacts { get; set; }
		[Ordinal(159)]  [RED("interestingFactsListenersIds")] public InterestingFactsListenersIds InterestingFactsListenersIds { get; set; }
		[Ordinal(160)]  [RED("interestingFactsListenersFunctions")] public InterestingFactsListenersFunctions InterestingFactsListenersFunctions { get; set; }
		[Ordinal(161)]  [RED("visionModeController")] public CHandle<PlayerVisionModeController> VisionModeController { get; set; }
		[Ordinal(162)]  [RED("cachedGameplayRestrictions")] public CArray<TweakDBID> CachedGameplayRestrictions { get; set; }
		[Ordinal(163)]  [RED("delayEndGracePeriodAfterSpawnEventID")] public gameDelayID DelayEndGracePeriodAfterSpawnEventID { get; set; }
		[Ordinal(164)]  [RED("bossThatTargetsPlayer")] public entEntityID BossThatTargetsPlayer { get; set; }
		[Ordinal(165)]  [RED("choiceTokenTextLayerId")] public CUInt32 ChoiceTokenTextLayerId { get; set; }
		[Ordinal(166)]  [RED("choiceTokenTextDrawn")] public CBool ChoiceTokenTextDrawn { get; set; }

		public PlayerPuppet(CR2WFile cr2w, CVariable parent, string name) : base(cr2w, parent, name) { }
	}
}
