using WolvenKit.RED4.CR2W.Reflection;
using FastMember;
using static WolvenKit.RED4.CR2W.Types.Enums;

namespace WolvenKit.RED4.CR2W.Types
{
	[REDMeta]
	public class interopGlobalNodeIDInfo : CVariable
	{
		private CString _globalName;
		private CString _globalNodeIDPath;
		private CUInt64 _globalNodeIDHash;
		private CBool _globalNameIsAutoGenerated;

		[Ordinal(0)] 
		[RED("globalName")] 
		public CString GlobalName
		{
			get
			{
				if (_globalName == null)
				{
					_globalName = (CString) CR2WTypeManager.Create("String", "globalName", cr2w, this);
				}
				return _globalName;
			}
			set
			{
				if (_globalName == value)
				{
					return;
				}
				_globalName = value;
				PropertySet(this);
			}
		}

		[Ordinal(1)] 
		[RED("globalNodeIDPath")] 
		public CString GlobalNodeIDPath
		{
			get
			{
				if (_globalNodeIDPath == null)
				{
					_globalNodeIDPath = (CString) CR2WTypeManager.Create("String", "globalNodeIDPath", cr2w, this);
				}
				return _globalNodeIDPath;
			}
			set
			{
				if (_globalNodeIDPath == value)
				{
					return;
				}
				_globalNodeIDPath = value;
				PropertySet(this);
			}
		}

		[Ordinal(2)] 
		[RED("globalNodeIDHash")] 
		public CUInt64 GlobalNodeIDHash
		{
			get
			{
				if (_globalNodeIDHash == null)
				{
					_globalNodeIDHash = (CUInt64) CR2WTypeManager.Create("Uint64", "globalNodeIDHash", cr2w, this);
				}
				return _globalNodeIDHash;
			}
			set
			{
				if (_globalNodeIDHash == value)
				{
					return;
				}
				_globalNodeIDHash = value;
				PropertySet(this);
			}
		}

		[Ordinal(3)] 
		[RED("globalNameIsAutoGenerated")] 
		public CBool GlobalNameIsAutoGenerated
		{
			get
			{
				if (_globalNameIsAutoGenerated == null)
				{
					_globalNameIsAutoGenerated = (CBool) CR2WTypeManager.Create("Bool", "globalNameIsAutoGenerated", cr2w, this);
				}
				return _globalNameIsAutoGenerated;
			}
			set
			{
				if (_globalNameIsAutoGenerated == value)
				{
					return;
				}
				_globalNameIsAutoGenerated = value;
				PropertySet(this);
			}
		}

		public interopGlobalNodeIDInfo(CR2WFile cr2w, CVariable parent, string name) : base(cr2w, parent, name) { }
	}
}
