name: publish-nuget
on:
  workflow_dispatch:

jobs:   

  check-console-win:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: build
      run: dotnet build .\WolvenKit.CLI\WolvenKit.CLI.csproj

    - name: publish nuget
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: .\WolvenKit.CLI\WolvenKit.CLI.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}
