name: stage changelog
on:
  workflow_dispatch:

env:
  PROJ: ./WolvenKit/WolvenKit.csproj
  GH_TOKEN: ${{ github.token }}

jobs:
  stage-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Cleanup branch
        run: |
          git push origin --delete changelog-staging || true
          git checkout -b changelog-staging

      - name: Precompile Changelog
        run: |
          pip install pyyaml
          python "tools/precompile_changelog.py" "changelog/unreleased" "changelog/!unreleased.yaml"

      - name: Ensure Changes exist
        shell: bash
        run: |
          if cmp -s 'changelog/!template.yaml' 'changelog/!unreleased.yaml'; then
            echo "No changes in changelog, aborting."
            exit 1
          fi

      - name: Get app version
        uses: naminodarie/get-net-sdk-project-versions-action@v2
        id: get_version
        with:
          proj-path: ${{env.PROJ}}

      - name: Set Version Variable
        shell: bash
        run: echo "VERSION_APP=${{steps.get_version.outputs.assembly-version}}" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          mkdir compiled-changelog
          echo ${{env.VERSION_APP}}
          python "tools/compile_changelog.py" --release ${{env.VERSION_APP}} --input "changelog/!unreleased.yaml" --out-md "changelog/generated/CHANGELOG.md" --out-bb "changelog/generated/CHANGELOG.txt" --changelog "CHANGELOG.md"

      - name: Name Unreleased
        shell: bash
        run: |
          mv 'changelog/!unreleased.yaml' "changelog/${VERSION_APP}.yaml"

      - name: Add Templated Unreleased
        shell: bash
        run: |
          cp 'changelog/!template.yaml' 'changelog/!unreleased.yaml'

      - name: Commit and Push
        run: |
          git add CHANGELOG.md
          git add changelog/
          git commit -m "Generate changelog for version ${{env.VERSION_APP}} and update source yaml files" || echo "No changes to commit"
          git push origin changelog-staging

      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head "changelog-staging" \
            --title "Generate changelog for ${{env.VERSION_APP}}" \
            --body "Generates user facing changelog entries and updates source yaml files. beep boop."
